-- Initial non-sensitive reference data for a clean environment.

-- Plans are intentionally excluded and must be registered directly in Production.

begin;

insert into public.essay_topics (id, title, axis, source_type, source_year, active, created_at)
values
  ('ad7aff01-ab14-4529-bcb4-05231109d885', 'Perspectivas acerca do envelhecimento na sociedade brasileira', 'Questões Sociais', 'ENEM', '2025', 't', '2026-02-04 04:31:01.603624+00'),
  ('9270cfa8-bb76-4982-8576-6a8f4d010df2', 'O movimento imigratório para o Brasil no Século XXI', 'Direitos e Cidadania', 'ENEM', '2012', 't', '2026-02-04 04:31:01.603624+00'),
  ('e1ca8ab7-6e63-4f7d-b2fc-3565cd6e86bb', 'Publicidade infantil em questão no Brasil', 'Direitos e Cidadania', 'ENEM', '2014', 't', '2026-02-04 04:31:01.603624+00'),
  ('839e2e1d-bf2d-4a17-9ce6-007a14a355c4', 'Desafios para o enfrentamento da invisibilidade do trabalho de cuidado realizado pela mulher no Brasil', 'Questões Sociais', 'ENEM', '2023', 't', '2026-02-04 04:31:01.603624+00'),
  ('f9108be2-a88b-4a1c-8ccf-e62c8d6bafa4', 'Desafios para a valorização de comunidades e povos tradicionais no Brasil', 'Direitos e Cidadania', 'ENEM', '2022', 't', '2026-02-04 04:40:58.912311+00'),
  ('b79143c3-c672-4c5f-bb48-a3d977e02a07', 'Democratização do acesso ao cinema no Brasil', 'Cultura', 'ENEM', '2019', 't', '2026-02-04 04:42:11.603657+00'),
  ('5ea7049e-24a1-4667-84d9-8f7ae0147fca', 'Caminhos para combater a intolerância religiosa no Brasil', 'Direitos e Cidadania', 'ENEM', '2016', 't', '2026-02-04 04:45:19.64272+00'),
  ('b12e5e0c-1447-492d-a0e3-8ca18668f12e', 'Invisibilidade e registro civil: garantia de acesso à cidadania no Brasil', 'Direitos e Cidadania', 'ENEM', '2021', 't', '2026-02-04 04:48:30.070259+00'),
  ('325cec75-f237-430c-be78-cf64eb5e496a', 'O estigma associado às doenças mentais na sociedade brasileira', 'Saúde', 'ENEM', '2020', 't', '2026-02-04 04:49:51.079317+00'),
  ('e8a9e590-8d01-4a97-a10c-e81c752a7ee8', 'A persistência da violência contra a mulher na sociedade brasileira', 'Direitos e Cidadania', 'ENEM', '2015', 't', '2026-02-04 04:51:57.325982+00'),
  ('ab69a868-661d-4ccb-8ba0-d15c19101b95', 'Desafios para a formação educacional de surdos no Brasil', 'Educação', 'ENEM', '2017', 't', '2026-02-04 04:53:25.474227+00'),
  ('2888cbfd-0563-48f7-9ad5-1d6312a1b75a', 'Manipulação do comportamento do usuário pelo controle de dados na internet', 'Tecnologia', 'ENEM', '2018', 't', '2026-02-04 04:54:38.357662+00'),
  ('1c8e26e3-eee5-48dc-a4be-f549d285af27', 'O indivíduo frente à ética nacional', 'Direitos e Cidadania', 'ENEM', '2009', 't', '2026-07-16 20:48:47.858066+00'),
  ('d8b0eb0d-8b99-4996-9921-65261e5f901f', 'O trabalho na construção da dignidade humana', 'Direitos e Cidadania', 'ENEM', '2010', 't', '2026-07-20 19:58:00.073541+00'),
  ('4b47ec2f-6a2b-4e82-9baf-f77a0ecba90e', 'Viver em rede no século XXI: os limites entre o público e o privado', 'Tecnologia', 'ENEM', '2011', 't', '2026-07-20 20:01:19.674364+00'),
  ('d3fd122f-a272-40a5-9172-56b4bc77f22c', 'Os efeitos da implantação da Lei Seca no Brasil', 'Direitos e Cidadania', 'ENEM', '2013', 't', '2026-02-04 04:31:01.603624+00'),
  ('7163e3f0-adf0-42c1-821b-7e608973a459', 'A família contemporânea e o que ela representa para a sociedade', 'Direitos e Cidadania', 'ENEM PPL', '2009', 't', '2026-07-20 20:07:31.863093+00'),
  ('e58b1ebb-68b2-4d37-a760-d8874ed771ec', 'Ajuda humanitária', 'Questões Sociais', 'ENEM PPL', '2010', 't', '2026-07-20 20:11:01.977279+00'),
  ('5eb9b76d-4890-4213-bb6d-46dda0c50093', 'Cultura e mudança social', 'Cultura', 'ENEM PPL', '2011', 't', '2026-07-20 20:16:08.812242+00'),
  ('88cd6b33-22ce-4bf7-8eb1-c4cedbfc40b8', 'O grupo fortalece o indivíduo?', 'Cultura', 'ENEM PPL', '2012', 't', '2026-07-20 20:18:16.2051+00'),
  ('b592af2b-c5bb-4525-9bc4-fa63a0fcbe22', 'Cooperativismo como alternativa social', 'Economia', 'ENEM PPL', '2013', 't', '2026-07-20 20:58:36.641294+00'),
  ('f7b84362-7fa2-43f2-adcc-515fbfdd2e24', 'O que o fenômeno social dos "rolezinhos" representa?', 'Questões Sociais', 'ENEM PPL', '2014', 't', '2026-07-20 21:03:33.664496+00'),
  ('5090fc5c-c69b-4499-b813-30b51ff9c81a', 'O histórico desafio de se valorizar o professor', 'Direitos e Cidadania', 'ENEM PPL', '2015', 't', '2026-07-20 21:05:52.033629+00'),
  ('e82694a8-9a7b-49dd-985b-08a77f9e01a8', 'Alternativas para a diminuição do desperdício de alimentos no Brasil', 'Meio Ambiente', 'ENEM PPL', '2016', 't', '2026-07-20 21:09:19.840151+00'),
  ('4a06b0f1-f1af-429c-af6c-4622a2a23fb2', 'Consequências da busca por padrões de beleza idealizados', 'Saúde', 'ENEM PPL', '2017', 't', '2026-07-20 21:13:55.505584+00'),
  ('d7dbaeb5-9331-432a-8454-0e3aa4031623', 'Formas de organização da sociedade para o enfrentamento de problemas econômicos no Brasil', 'Economia', 'ENEM PPL', '2018', 't', '2026-07-20 21:23:38.891271+00'),
  ('1a4d3b3f-633b-4634-ab54-3beb3bd98dee', 'Falta de empatia nas relações sociais no Brasil', 'Questões Sociais', 'ENEM PPL', '2020', 't', '2026-07-20 21:32:46.311625+00'),
  ('846cc34e-c7c4-4f14-8dc9-94382a68ce82', 'Combate ao uso indiscriminado das tecnologias digitais de informação por crianças', 'Tecnologia', 'ENEM PPL', '2019', 't', '2026-07-20 21:30:15.410961+00'),
  ('7bfdf552-60e6-420d-a951-f57ad080b0c1', 'Reconhecimento da contribuição das mulheres nas ciências da saúde no Brasil', 'Saúde', 'ENEM PPL', '2021', 't', '2026-07-20 21:41:41.002597+00'),
  ('a16ef606-d9f3-452a-a735-f8b28f28a973', 'Medidas para o enfrentamento da recorrência da insegurança alimentar no Brasil', 'Direitos e Cidadania', 'ENEM PPL', '2022', 't', '2026-07-20 22:10:53.339367+00'),
  ('e8107cbf-03ca-4d8c-af98-096ce82ebdd5', 'Desafios para a (re)inserção socioeconômica da população em situação de rua no Brasil', 'Economia', 'ENEM PPL', '2023', 't', '2026-07-20 22:16:51.433793+00'),
  ('cc651d5e-6a89-45ab-ba7e-2317475adad8', 'Desafios para a valorização da arte de periferia no cenário cultural brasileiro', 'Cultura', 'ENEM PPL', '2024', 't', '2026-07-20 22:20:02.849571+00'),
  ('84de40f9-f257-421a-890b-384a79e38dfc', 'A idade mínima para o trabalho como forma de proteção à infância', 'Direitos e Cidadania', 'ENEM PPL', '2025', 't', '2026-07-20 22:28:01.865541+00')
on conflict (id) do update set
  title = excluded.title,
  axis = excluded.axis,
  source_type = excluded.source_type,
  source_year = excluded.source_year,
  active = excluded.active,
  created_at = excluded.created_at;

insert into public.motivational_texts (id, topic_id, text_number, body_text, image_url, source_reference)
values
  ('0403e987-c06e-468c-a336-4d85f513b8d5', 'ad7aff01-ab14-4529-bcb4-05231109d885', '1', 'Em 2022, o total de pessoas com 65 anos de idade ou mais no pais chegou a 10,9% da população, com alta de 57,4% frente a 2010, quando esse contingente era 7,4% da população. É o que revelam os resultados do universo da população do Brasil desagregada por idade e sexo do Censo Demográfico 2022. "O Estatuto do Idoso define como idoso a pessoa de 60 anos ou mais. O corte de 65 anos ou mais foi utilizado nessa análise para manter comparabilidade internacional e com outras pesquisas que utilizam essa faixa etária, como de mercado de trabalho", justifica a gerente de Estudos e Análises da Dinâmica Demográfica do IBGE. O aumento da população de 65 anos ou mais e a diminuição da parcela da população de até 14 anos no mesmo período, que passou de 24,1% para 19,8%, evidenciam o franco envelhecimento da população brasileira.', null, 'GOMES, I.; BRITTO, V. Censo 2022. Disponível em: https://agenciadenoticias.ibge.gov.br.'),
  ('fbce29f5-0039-4550-af90-b1941167cccd', 'ad7aff01-ab14-4529-bcb4-05231109d885', '2', 'Dona Maria Rita era tão antiga que na casa da filha estavam habituados a ela como a um móvel velho. Ela não era novidade para ninguém. Mas nunca lhe passara pela cabeça que era uma solitária. Só que não tinha nada para fazer. Era um lazer forçado que em certos momentos se tornava lancinante: nada tinha a fazer no mundo. Senão viver como um gato, como um cachorro. Seu ideal era ser dama de companhia de alguma senhora, mas isso nem se usava mais e mesmo ninguém acreditaria nos seus fortes setenta e sete anos, pensariam que era uma fraca. Não fazia nada, fazia só isso: ser velha. Às vezes ficava deprimida achava que não servia a nada, não servia sequer a Deus.', null, 'LISPECTOR, C. Onde estivestes de noite.'),
  ('a5404389-07db-49e4-8482-1ff9051f0363', '9270cfa8-bb76-4982-8576-6a8f4d010df2', '1', 'Ao desembarcar no Brasil, os imigrantes trouxeram muito mais do que o anseio de refazer suas vidas trabalhando nas lavouras de café e no início da indústria paulista. Nos séculos XIX e XX, os representantes de mais de 70 nacionalidades e etnias chegaram com o sonho de “fazer a América” e acabaram por contribuir expressivamente para a história do país e para a cultura brasileira. Deles, o Brasil herdou sobrenomes, sotaques, costumes, comidas e vestimentas. A história da migração humana não deve ser encarada como uma questão relacionada exclusivamente ao passado; há a necessidade de tratar sobre deslocamentos mais recentes.', null, 'Disponível em: http://www.museudaimigracao.org.br. Acesso em: 19 jul. 2012 (adaptado).'),
  ('14c72975-e30a-41a2-97ff-e9b3fd5f400c', 'ad7aff01-ab14-4529-bcb4-05231109d885', '3', null, 'enem-2025-motivador-2.jpg', null),
  ('68b0e811-af6a-4769-a6bb-02401e2dbe5c', '9270cfa8-bb76-4982-8576-6a8f4d010df2', '2', null, 'enem-2012-motivador-2.png', 'Disponível em: http://mg1.com.br. Acesso em: 19 jul. 2012'),
  ('7c031aa8-2589-4fe4-b2bd-8822ea7340fc', 'b79143c3-c672-4c5f-bb48-a3d977e02a07', '1', null, 'enem-2019-motivador-3.png', 'Disponível em: www.meioemensagem.com. Acesso em: 12 jun. 2019 (adaptado).'),
  ('c6782cba-e844-40a1-aa5f-db9cc59a5a5f', 'ad7aff01-ab14-4529-bcb4-05231109d885', '4', 'A velhice é tempo de se retratar consigo mesma, de falar da doença, da sexualidade, do tédio e da liberdade de não se encaixar mais nas expectativas sociais. "A velhice não é doença. É destino", escreve Rita Lee. Mas ela mesma mostra que esse destino não é sinônimo de mero encaminhamento para o fim - é campo de novas escolhas, inclusive a de desafiar estereótipos reservados para essa fase da vida. 

A atriz Fernanda Montenegro, 95 anos, oferece em suas memórias uma síntese luminosa desse gesto de habitar o tempo com dignidade: "A velhice é o tempo em que a vida já foi vivida e, por isso mesmo, pode finalmente ser olhada de frente, sem o pânico do ineditismo".', null, null),
  ('cd78f440-ae80-47cf-9409-984e84e7d946', 'ad7aff01-ab14-4529-bcb4-05231109d885', '5', 'Quem tem direito de viver mais? 

O documentário Quantos dias. Quantas noites bus- investigar quem, afinal, tem direito a uma vida longa no Brasil, "São inúmeros os marcadores que definem quem vai viver, quem vai sucumbir diante de uma realidade imposta por sistema bastante perverso", afirma o diretor do documentário. 
"O envelhecimento leva a maioria das pessoas a declínio funcional. Mas, se você chega aos 75 tendo acumulado desigualdades, principalmente pelo racismo, é muito diferente sobreviver com qualidade de vida", diz um médico gerontólogo.', null, 'Disponível em: g1.globo.com. Acesso em: 10 jun. 2025 (adaptado).'),
  ('4199d53b-8bdd-4d93-a2f1-eedff47b41c9', '9270cfa8-bb76-4982-8576-6a8f4d010df2', '3', 'Acre sofre com invasão de imigrantes do Haiti. Nos últimos três dias de 2011, uma leva de 500 haitianos entrou ilegalmente no Brasil pelo Acre, elevando para 1 400 a quantidade de imigrantes daquele país no município de Brasileia (AC). Segundo o secretário-adjunto de Justiça e Direitos Humanos do Acre, José Henrique Corinto, os haitianos ocuparam a praça da cidade. A Defesa Civil do estado enviou galões de água potável e alimentos, mas ainda não providenciou abrigo. A imigração ocorre porque o Haiti ainda não se recuperou dos estragos causados pelo terremoto de janeiro de 2010. O primeiro grande grupo de haitianos chegou a Brasileia no dia 14 de janeiro de 2011. Desde então, a entrada ilegal continua, mas eles não são expulsos: obtêm visto humanitário e conseguem tirar carteira de trabalho e CPF para morar e trabalhar no Brasil. Segundo Corinto, ao contrário do que se imagina, não são haitianos miseráveis que buscam o Brasil para viver, mas pessoas da classe média do Haiti e profissionais qualificados, como engenheiros, professores, advogados, pedreiros, mestres de obras e carpinteiros. Porém, a maioria chega sem dinheiro. Os brasileiros sempre criticaram a forma como os países europeus tratavam os imigrantes. Agora, chegou a nossa vez — afirma Corinto.', null, 'Disponível em: http://www.dpf.gov.br. Acesso em: 19 jul. 2012 (adaptado).'),
  ('470fd3ce-f2e5-428c-ba5c-e3b13fb20910', 'e1ca8ab7-6e63-4f7d-b2fc-3565cd6e86bb', '1', 'A aprovação, em abril de 2014, de uma resolução que considera abusiva a publicidade infantil, emitida pelo Conselho Nacional de Direitos da Criança e do Adolescente (Conanda), deu início a um verdadeiro cabo de guerra envolvendo ONGs de defesa dos direitos das crianças e setores interessados na continuidade das propagandas dirigidas a esse público. Elogiada por pais, ativistas e entidades, a resolução estabelece como abusiva toda propaganda dirigida à criança que tem “a intenção de persuadi-la para o consumo de qualquer produto ou serviço” e que utilize aspectos como desenhos animados, bonecos, linguagem infantil, trilhas sonoras com temas infantis, oferta de prêmios, brindes ou artigos colecionáveis que tenham apelo às crianças. Ainda há dúvidas, porém, sobre como será a aplicação prática da resolução. E associações de anunciantes, emissoras, revistas e de empresas de licenciamento e fabricantes de produtos infantis criticam a medida e dizem não reconhecer a legitimidade constitucional do Conanda para legislar sobre publicidade e para impor a resolução tanto às famílias quanto ao mercado publicitário. Além disso, defendem que a autorregulamentação pelo Conselho Nacional de Autorregulamentação Publicitária (Conar) já seria uma forma de controlar e evitar abusos.', null, 'IDOETA, P. A.; BARBA, M. D. A publicidade infantil deve ser proibida? Disponível em: www.bbc.co.uk. Acesso em: 23 maio 2014 (adaptado).'),
  ('d9036720-a9e2-4e6c-b19d-7805e4177111', 'e1ca8ab7-6e63-4f7d-b2fc-3565cd6e86bb', '2', 'Precisamos preparar a criança, desde pequena, para receber as informações do mundo exterior, para compreender o que está por trás da divulgação de produtos. Só assim ela se tornará o consumidor do futuro, aquele capaz de saber o que, como e por que comprar, ciente de suas reais necessidades e consciente de suas responsabilidades consigo mesma e com o mundo.', null, 'SILVA, A. M. D.; VASCONCELOS, L. R. A criança e o marketing: informações essenciais para proteger as crianças dos apelos do marketing infantil. São Paulo: Summus, 2012 (adaptado).'),
  ('3fdc4598-95c1-4d8e-96d8-aa366bfbc606', '839e2e1d-bf2d-4a17-9ce6-007a14a355c4', '1', 'A sociedade brasileira tem passado por inúmeras transformações sociais ao longo das últimas décadas. Entre elas, as percepções sociais a respeito dos valores e das convenções de gênero e a forma como mulheres têm se inserido na sociedade. Algumas permanências, porém, chamam a atenção, como a delegação quase que exclusiva às famílias - e, nestas, às mulheres - de atividades relacionadas à reprodução da vida e da sociedade, usualmente nominadas trabalho de cuidado.', null, 'Disponível em: https://repositorio.ipea.gov.br/handle/11058/7412 (adaptado).'),
  ('4dab7354-4784-40e6-851d-73098b4a5ec8', '839e2e1d-bf2d-4a17-9ce6-007a14a355c4', '2', null, 'enem-2023-motivador-4.png', 'Capa da revista Pesquisa. Disponível em: https://revistapesquisa.fapesp.br. Acesso em: 23 maio 2023 (adaptado).'),
  ('856c335d-cbd4-4564-be0e-0520592cc897', 'ad7aff01-ab14-4529-bcb4-05231109d885', '6', 'Um novo estereótipo: o "velho ativo", saudável e com recursos pressiona o "velho inativo", doente e pobre. Nem todos os idosos têm recursos à disposição para aderir a essa corrida. Idosos são os principais mantenedores dos lares', 'enem-2025-motivador-4.jpg', 'Disponível em: g1.globo.com. Acesso em: 4 jun. 2025 (adaptado)'),
  ('c52b51a8-e7bc-417e-94d4-065df69a2749', 'e1ca8ab7-6e63-4f7d-b2fc-3565cd6e86bb', '3', null, 'enem-2014-motivador-2.png', 'Disponível em: www1.folha.uol.com.br. Acesso em: 24 jun. 2014 (adaptado).'),
  ('e27e3c6e-2a27-466b-9754-b384a2e7e2ed', '839e2e1d-bf2d-4a17-9ce6-007a14a355c4', '3', null, 'enem-2023-motivador-2.png', 'Disponível em: https://agenciadenoticias.ibge.gov.br. Acesso em: 18 de jul. 2023 (adaptado).'),
  ('73e766f1-8d78-4e0d-a062-00873c5ef4d0', '839e2e1d-bf2d-4a17-9ce6-007a14a355c4', '4', 'O trabalho de cuidado não remunerado e mal pago e a crise global da desigualdade

O trabalho de cuidado é essencial para nossas sociedades e para a economia. Ele inclui o trabalho de cuidar de crianças, idosos e pessoas com doenças e deficiências físicas e mentais, bem como o trabalho doméstico diário que inclui cozinhar, limpar, lavar, consertar coisas e buscar água e lenha. Se ninguém investisse tempo, esforços e recursos nessas tarefas diárias essenciais, comunidades, locais de trabalho e economias inteiras ficariam estagnados. Em todo o mundo, o trabalho de cuidado não remunerado e mal pago é desproporcionalmente assumido por mulheres e meninas em situação de pobreza, especialmente por aquelas que pertencem a grupos que, além da discriminação de gênero, sofrem preconceito em decorrência de sua raça, etnia, nacionalidade e sexualidade. As mulheres são responsáveis por mais de três quartos do cuidado não remunerado e compõem dois terços da força de trabalho envolvida em atividades de cuidado remuneradas.', null, 'Disponível em: https://www.oxfam.org.br/publicacao/tempo-de-cuidar-o-trabalho-de-cuidado-nao-remunerado-e-mal-pago-e-a-crise-global-da-desigualdade/ (adaptado).'),
  ('f34dbaa8-4641-490b-83fe-7234aed9b7d2', '5090fc5c-c69b-4499-b813-30b51ff9c81a', '1', null, 'enem-ppl-2015-motivador-1.jpg', 'Disponível em: http://www.sinpro-rs.org.br. Acesso em: 26 jun. 2015 (adaptado)'),
  ('ab6437a3-920e-41d2-be32-6e78f0a9a274', '5090fc5c-c69b-4499-b813-30b51ff9c81a', '2', 'O estatuto social e econômico é a chave para o estudo dos professores e da sua profissão. Num olhar rápido temos a impressão que a imagem social e a condição econômica dos professores se encontram num estado de grande degradação. E este sentimento é confirmado por certos discursos das organizações sindicais e mesmo das autoridades estatais. Mas, cada vez que a análise é mais fina, os resultados são menos concludentes e a profissão docente continua a revelar facetas atrativas. É evidente que há uma perda de prestígio, associada à alteração do papel tradicional dos professores no meio local. Os professores do ensino primário já não são, ao lado dos párocos, os únicos agentes culturais nas aldeias e vilas da província. Os professores do ensino secundário já não pertencem à elite social das cidades.', null, 'NÓVOA, A. O passado e o presente dos professores. In NÓVOA, A. (Ed.). Porto: Porto Editora, 1995 (adaptado).'),
  ('f1095674-e80a-4ba3-97ac-f9cc00679774', 'f9108be2-a88b-4a1c-8ccf-e62c8d6bafa4', '1', null, 'enem-2022-motivador-2.png', 'Disponível em: https://g1.globo.com. Acesso em: 17 jun. 2022 (adaptado).'),
  ('6f582420-e6b4-46b0-ba32-6e684e484a23', 'b79143c3-c672-4c5f-bb48-a3d977e02a07', '2', 'No dia da primeira exibição pública de cinema — 28 de dezembro de 1895, em Paris —, um homem de teatro que trabalhava com mágicas, Georges Mélies, foi falar com Lumière, um dos inventores do cinema; queria adquirir um aparelho, e Lumière desencorajou-o, disse-lhe que o “Cinematógrapho” não tinha o menor futuro como espetáculo, era um instrumento científico para reproduzir o movimento e só poderia servir para pesquisas. Mesmo que o público, no início, se divertisse com ele, seria uma novidade de vida breve, logo cansaria. Lumière enganou-se. Como essa estranha máquina de austeros cientistas virou uma máquina de contar estórias para enormes plateias, de geração em geração, durante já quase um século?', null, 'BERNARDET, Jean-Claude. O que é Cinema. In BERNARDET, Jean-Claude; ROSSI, Clóvis. O que é Jornalismo, O que é Editora, O que é Cinema. São Paulo: Brasiliense, 1993.'),
  ('8ba13eeb-df42-40a9-9c25-763a4135b7e9', 'b79143c3-c672-4c5f-bb48-a3d977e02a07', '3', 'Edgar Morin define o cinema como uma máquina que registra a existência e a restitui como tal, porém levando em consideração o indivíduo, ou seja, o cinema seria um meio de transpor para a tela o universo pessoal, solicitando a participação do espectador.', null, 'GUTFREIND, C. F. O filme e a representação do real. E-Compós, v. 6, 11, 2006 (adaptado).'),
  ('75a9f8fc-0b49-4383-90c6-da32c0dabf5a', 'f9108be2-a88b-4a1c-8ccf-e62c8d6bafa4', '2', 'Povos e comunidades tradicionais

O Ministério do Desenvolvimento Social (MDS) preside, desde 2007, a Comissão Nacional de Desenvolvimento Sustentável das Comunidades Tradicionais (CNPCT), criada em 2006. Fruto dos trabalhos da CNPCT, foi instituída, por meio do Decreto 6.040, de 7 de fevereiro de 2017, a Política Nacional de Desenvolvimento Sustentável dos Povos e Comunidades Tradicionais (PNPCT). A PNPCT foi criada em um contexto de busca de reconhecimento e preservação de outras formas de organização social por parte do Estado. ', null, 'Disponível em: http://mds.gov.br (adaptado).'),
  ('b38133aa-fb06-4d08-8eaf-93694e6446f1', 'b79143c3-c672-4c5f-bb48-a3d977e02a07', '4', 'O Brasil já teve um parque exibidor vigoroso e descentralizado: quase 3 300 salas em 1975, uma para cada 30 000 habitantes, 80% em cidades do interior. Desde então, o país mudou. Quase 120 milhões de pessoas a mais passaram a viver nas cidades. A urbanização acelerada, a falta de investimentos em infraestrutura urbana, a baixa capitalização das empresas exibidoras, as mudanças tecnológicas, entre outros fatores, alteraram a geografia do cinema. Em 1997, chegamos a pouco mais de 1 000 salas. Com a expansão dos shopping centers, a atividade de exibição se reorganizou. O número de cinemas duplicou, até chegar às atuais 2 200 salas. Esse crescimento, porém, além de insuficiente (o Brasil é apenas o 60º país na relação habitantes por sala), ocorreu de forma concentrada. Foram privilegiadas as áreas de renda mais alta das grandes cidades. Populações inteiras foram excluídas do universo do cinema ou continuam mal atendidas: o Norte e o Nordeste, as periferias urbanas, as cidades pequenas e médias do interior.', null, 'Disponível em: https://cinemapertodevoce.ancine.gov.br. Acesso em: 13 jun. 2019 (fragmento).'),
  ('44125e51-70b2-4121-8d83-19685dd702bd', '5ea7049e-24a1-4667-84d9-8f7ae0147fca', '1', 'Em consonância com a Constituição da República Federativa do Brasil e com toda a legislação que assegura a liberdade de crença religiosa às pessoas, além de proteção e respeito às manifestações religiosas, a laicidade do Estado deve ser buscada, afastando a possibilidade de interferência de correntes religiosas em matérias sociais, políticas, culturais etc.', null, 'Disponível em: www.mprj.mp.br. Acesso em: 21 maio 2016 (fragmento).'),
  ('b2d89961-6db5-41d2-8019-6eee330d2120', '5ea7049e-24a1-4667-84d9-8f7ae0147fca', '2', 'O direito de criticar dogmas e encaminhamentos é assegurado como liberdade de expressão, mas atitudes agressivas, ofensas e tratamento diferenciado a alguém em função de crença ou de não ter religião são crimes inafiançáveis e imprescritíveis.', null, 'STECK, J. Intolerância religiosa é crime de ódio e fere a dignidade. Jornal do Senado. Acesso em: 21 maio 2016 (fragmento).'),
  ('46f3d09b-2a94-4a3e-a0b3-ab046f1dccc5', '5ea7049e-24a1-4667-84d9-8f7ae0147fca', '3', null, 'enem-2016-motivador-4.png', 'Disponível em: www1.folha.uol.com.br. Acesso em: 31 maio 2016 (adaptado).'),
  ('289b0d21-d045-462e-b178-c31d2e0aebeb', 'b12e5e0c-1447-492d-a0e3-8ca18668f12e', '1', 'A certidão de nascimento é o primeiro e o mais importante documento do cidadão. Com ele, a pessoa existe oficialmente para o Estado e a sociedade. Só de posse da certidão é possível retirar outros documentos civis, como a carteira de trabalho, a carteira de identidade, o título de eleitor e o Cadastro de Pessoa Física (CPF). Além disso, para matricular uma criança na escola e ter acesso a benefícios sociais, a apresentação do documento é obrigatória.', null, 'Disponível em: https://www2.senado.leg.br/bdsf/handle/id/70224 (adaptado).'),
  ('ffa8a44d-3994-480c-b905-a6b961515bcd', '325cec75-f237-430c-be78-cf64eb5e496a', '1', 'A maior parte das pessoas, quando houve falar em "saúde mental", pensa em "doença mental". Mas a saúde mental implica muito mais que a ausência de doenças mentais. Pessoas mentalmente saudáveis compreendem que ninguém é perfeito, que todos possuem limites e que não se pode ser tudo para todos. Elas vivenciam diariamente uma série de emoções como alegria, amor, satisfação, tristeza, raiva e frustração. São capazes de enfrentar os desafios e as mudanças da vida cotidiana com equilíbrio e sabem procurar ajuda quando têm dificuldade em lidar com conflitos, perturbações, traumas ou transições importantes nos diferentes ciclos da vida. A saúde mental de uma pessoa está relacionada à forma como ela reage às exigências da vida e ao modo como harmoniza seus desejos, capacidades, ambições, ideias e emoções. Todas as pessoas podem apresentar sinais de sofrimento psíquico em alguma fase da vida.', null, 'Disponível em: https://www.saude.pr.gov.br/ (adaptado).'),
  ('0810d425-e829-48f3-91a8-234641e184dd', '2888cbfd-0563-48f7-9ad5-1d6312a1b75a', '1', 'Mudanças sutis nas informações às quais somos expostos podem transformar nosso comportamento. As redes têm selecionado as notícias sob titulos chamativos como “trending topics” ou critérios como “relevância”. Mas nós praticamente não sabemos como tudo isso é filtrado. Quanto mais informações relevantes tivermos nas pontas dos dedos, melhor equipados estamos para tomar decisões. No entanto, surgem algumas tensões fundamentais: entre a conveniência e a deliberação; entre o que o usuário deseja e o que é melhor para ele; entre a transparência e o lado comercial. Quanto mais os sistemas souberem sobre você em comparação ao que você sabe sobre eles, há mais riscos de suas escolhas se tornarem apenas uma série de reações a “cutucadas” invisíveis. O que está em jogo não é tanto a questão “homem versus máquina”, mas sim a disputa “decisão informada versus obediência influenciada”.', null, 'CHATFIELD, Tom. Como a Internet influencia secretamente nossas escolhas. Disponível em: www.bbc.com. Acesso em: 3 jun. 2017 (adaptado).'),
  ('7dcc6720-bc75-4875-b36a-ad846c18ccc3', '5ea7049e-24a1-4667-84d9-8f7ae0147fca', '4', 'CAPÍTULO I. Dos Crimes Contra o Sentimento Religioso
Ultraje a culto e impedimento ou perturbação de ato a ele relativo
Art. 208 - Escarnecer de alguém publicamente, por motivo de crença ou função religiosa; impedir ou perturbar cerimônia ou prática de culto religioso; vilipendiar publicamente ato ou objeto de culto religioso:
Pena - detenção, de um mês a um ano, ou multa.
Parágrafo único - Se há emprego de violência, a pena é aumentada de um terço, sem prejuízo da correspondente à violência.', null, 'BRASIL. Código Penal. Disponível em: www.planalto.gov.br. Acesso em: 21 maio 2016 (fragmento)'),
  ('dca17ac9-308b-4294-b758-0e526a2bbd76', 'b12e5e0c-1447-492d-a0e3-8ca18668f12e', '2', null, 'enem-2021-motivador-4.png', 'Disponível em: https://www.ufrgs.br/humanista/2018/07/16/brasil-esta-proximo-de-erradicar-o-subregistro-civil-de-nascimentos/'),
  ('fe0be56d-eff4-48ba-9721-e13e337948b2', '325cec75-f237-430c-be78-cf64eb5e496a', '2', null, 'enem-2020-motivador-3.png', 'Disponível em: https://zenklub.com.br/ (adaptado).'),
  ('57accf58-b091-48b1-853c-d6bd87e9ea98', 'e8a9e590-8d01-4a97-a10c-e81c752a7ee8', '1', 'Nos 30 anos decorridos entre 1980 e 2010 foram assassinadas no país acima de 92 mil mulheres, 43,7 mil só na última década. O número de mortes nesse período passou de 1.353 para 4.465, que representa um aumento de 230%, mais que triplicando o quantitativo de mulheres vítimas de assassinato no país.', null, 'WALSELFISZ, J. J. Mapa da Violência 2012. Atualização: Homicídio de mulheres no Brasil. Disponível em: www.mapadaviolencia.org.br. Acesso em: 8 jun. 2015.'),
  ('0da83f7d-0b53-49ab-88a3-055b80a0a6a3', 'e8a9e590-8d01-4a97-a10c-e81c752a7ee8', '2', null, 'enem-2015-motivador-2.png', 'BRASIL. Secretaria de Políticas para as Mulheres. Balanço 2014. Central de Atendimento à Mulher: Disque 180. Brasília, 2015. Disponível em: www.spm.gov.br. Acesso em: 24 jun. 2015 (adaptado).'),
  ('63064970-1edc-4212-b137-c7c155c8473b', 'e8a9e590-8d01-4a97-a10c-e81c752a7ee8', '3', null, 'enem-2015-motivador-3.png', 'Disponível em: www.compromissoeatitude.org.br. Acesso em: 24 jun. 2015 (adaptado).'),
  ('bb5e7e86-ca50-4d04-a7a0-291742f3a593', 'ab69a868-661d-4ccb-8ba0-d15c19101b95', '1', 'CAPÍTULO IV - DO DIREITO À EDUCAÇÃO. Art. 27. A educação constitui direito da pessoa com deficiência, assegurados sistema de educação inclusivo em todos os níveis e aprendizado ao longo de toda a vida, de forma a alcançar o máximo desenvolvimento possível de seus talentos e habilidades físicas, sensoriais, intelectuais e sociais, segundo suas características, interesses e necessidades de aprendizagem. Parágrafo único. É dever do Estado, da família, da comunidade escolar e da sociedade assegurar educação de qualidade à pessoa com deficiência, colocando-a a salvo de toda forma de violência, negligência e discriminação. Art. 28. Incumbe ao poder público assegurar, criar, desenvolver, implementar, incentivar, acompanhar e avaliar: […] IV – oferta de educação bilíngue, em Libras como primeira língua e na modalidade escrita da língua portuguesa como segunda língua, em escolas e classes bilíngues e em escolas inclusivas; […] XII – oferta de ensino da Libras, do Sistema Braille e de uso de recursos de tecnologia assistiva, de forma a ampliar habilidades funcionais dos estudantes, promovendo sua autonomia e participação.', null, 'BRASIL. Lei nº 13.146, de 6 de julho de 2015. Disponível em: www.planalto.gov.br. Acesso em: 9 jun. 2017 (fragmento).'),
  ('484a5957-e962-4ac0-ab78-0f2cb1b3c6ba', 'ab69a868-661d-4ccb-8ba0-d15c19101b95', '2', null, 'enem-2017-motivador-2.png', 'Fonte: Inep.'),
  ('b55237de-0b9f-4ec4-88d6-0f81b1b57b67', 'ab69a868-661d-4ccb-8ba0-d15c19101b95', '3', null, 'enem-2017-motivador-3.png', 'Disponível em: http://servicos.prt4.mpt.mp.br. Acesso em: 3 jun. 2017 (adaptado).'),
  ('dcffa6c8-760f-4ac8-8d0c-c065eb12bb21', 'ab69a868-661d-4ccb-8ba0-d15c19101b95', '4', 'No Brasil, os surdos só começaram a ter acesso à educação durante o Império, no governo de Dom Pedro II, que criou a primeira escola de educação de meninos surdos, em 26 de setembro de 1857, na antiga capital do País, o Rio de Janeiro. Hoje, no lugar da escola funciona o Instituto Nacional de Educação de Surdos (Ines). Por isso, a data foi escolhida como Dia do Surdo. Contudo, foi somente em 2002, por meio da sanção da Lei nº 10.436, que a Língua Brasileira de Sinais (Libras) foi reconhecida como segunda língua oficial no País. A legislação determinou também que devem ser garantidas, por parte do poder público em geral e empresas concessionárias de serviços públicos, formas institucionalizadas de apoiar o uso e difusão da Libras como meio de comunicação objetiva.', null, 'Disponível em: www.brasil.gov.br. Acesso em: 9 jun. 2017 (adaptado).'),
  ('48b92ad0-ac8d-4042-bf62-296aaa3a6a32', '2888cbfd-0563-48f7-9ad5-1d6312a1b75a', '2', 'Às segundas-feiras pela manhã, os usuários de um serviço de música digital recebem uma lista personalizada de músicas que lhes permite descobrir novidades. Assim como os sistemas de outros aplicativos e redes sociais, este cérebro artificial consegue traçar um retrato automatizado do gosto de seus assinantes e constrói uma máquina de sugestões que não costuma falhar. O sistema se baseia em um algoritmo cuja evolução e usos aplicados ao consumo cultural são infinitos. De fato, plataformas de transmissão de video on-line começam a desenhar suas séries de sucesso rastreando o banco de dados gerado por todos os movimentos dos usuários para analisar o que os satisfaz. O algoritmo constrói assim um universo cultural adequado e complacente com o gosto do consumidor, que pode avançar até chegar sempre a lugares reconhecíveis. Dessa forma, a filtragem feita pelas redes sociais ou pelos sistemas de busca pode moldar nossa maneira de pensar. E esse é o problema principal: a ilusão da liberdade de escolha que muitas vezes é gerada pelos algoritmos.', null, 'VERDÚ, Daniel. O gosto na era do algoritmo. Disponível em: https://brasil.elpais.com. Acesso em: 11 jun. 2018 (adaptado).'),
  ('43bdda55-e7d3-4c37-a548-30f5408fa318', '2888cbfd-0563-48f7-9ad5-1d6312a1b75a', '3', 'Nos sistemas dos gigantes da internet, a filtragem de dados é transferida para um exército de moderadores em empresas localizadas do Oriente Médio ao Sul da Ásia, que têm um papel importante no controle daquilo que deve ser eliminado da rede social, a partir de sinalizações dos usuários. Mas a informação é então processada por um algoritmo, que tem a decisão final. Os algoritmos são literais. Em poucas palavras, são uma opinião embrulhada em código. E estamos caminhando para um estágio em que é a máquina que decide qual notícia deve ou não ser lida.', null, 'PEPE ESCOBAR. A silenciosa ditadura do algoritmo. Disponível em: https://outraspalavras.net. Acesso em: 5 jun. 2017 (adaptado).'),
  ('950fe62c-bed2-4eb2-a214-f453674ddfcd', '2888cbfd-0563-48f7-9ad5-1d6312a1b75a', '4', null, 'enem-2018-motivador-3.png', 'Internet no Brasil em 2016. Disponível em: www.ibge.gov.br. Acesso em: 18 jun. 2018 (adaptado).'),
  ('4f7902fd-e746-4222-8d84-3b752bdfa837', 'b12e5e0c-1447-492d-a0e3-8ca18668f12e', '3', 'A Lei de número 9534 de 1997 tornou o registro de nascimento gratuito no Brasil. Só que o problema persiste, mostrando que essa exclusão é complexa e não se explica apenas pela dificuldade financeira em pagar pelo registro, por exemplo.', 'enem-2021-motivador-2 .png', 'Disponível em: https://estudio.r7.com/os-invisiveis-10082020 (adaptado).'),
  ('b7a6ab4d-bc96-4991-b03a-dad03f15d5ae', '325cec75-f237-430c-be78-cf64eb5e496a', '3', 'A origem da palavra "estigma" aponta para marcas ou cicatrizes deixadas por feridas. Por extensão, em um período que remonta à Grécia Antiga, passou a designar também as marcas feitas com ferro em brasa em criminosos, escravos e outras pessoas que se desejava separar da sociedade "correta" e "honrada". Essa mesma palavra muitas vezes está presente no universo das doenças psiquiátricas. No lugar da marca de ferro, relegamos preconceito, falta de informação e tratamentos precários a pessoas que sofrem de depressão, ansiedade, transtorno bipolar e outros transtornos mentais graves. 

Achar que a manifestação de um transtorno mental é "frescura" está relacionado a um ideal de felicidade que não é igual para todo mundo. A tentativa de se encaixar nesse modelo cria distância dos sentimentos reais, e quem os demonstra é rotulado, o que progressivamente dificulta a interação social. É aqui que redes sociais de enorme popularidade mostram uma face cruel, desempenhando um papel de validação da vida perfeita e criando um ambiente em que tudo deve ser mostrado em seu melhor ângulo. Fora dos holofotes da internet, porém, transtornos mentais mostram-se mais presentes do que se imagina.', null, 'Disponível em: https://www.abrata.org.br/ (adaptado).'),
  ('d6a5b415-768a-412f-a41b-f080395c1626', 'b12e5e0c-1447-492d-a0e3-8ca18668f12e', '4', 'Toda sexta-feira, o ônibus azul e branco estacionado no pátio da Vara da Infância e da Juventude, na Praça Onze, Centro do Rio, sacoleja com o entra e sai de gente a partir das 9h. Do lado de fora, nunca menos de 50 pessoas, todas pobres ou muito pobres, quase todas negras, cercam o veículo, perguntam, sentam e levantam, perguntam de novo e esperam sem reclamar o tempo que for preciso. Adultos, velhos e crianças estão ali para conseguir o que, no Brasil, é oficialmente reconhecido como o primeiro documento da vida - a certidão de nascimento. (...) 

Ao longo do discurso desses entrevistados, fica clara a forma como os usuários se definem: "zero à esquerda", "cachorro", "um nada", "pessoa que não existe", entre outras, todas são expressões que conformam claramente a ideia da pessoa sem registro de nascimento sobre si mesma como uma pessoa sem valor, cuja existência nunca foi oficialmente reconhecida pelo Estado.', null, 'Disponível em: ESCÓSSIA, F. M. Invisíveis: uma etnografia sobre identidade, direitos e cidadania nas trajetórias de brasileiros sem documento. Tese (Doutorado em História, Política e Bens Culturais). Fundação Getúlio Vargas. Rio de Janeiro. 2019.'),
  ('3c8e53d0-b69f-47a3-845c-8c7e11ddadac', 'f9108be2-a88b-4a1c-8ccf-e62c8d6bafa4', '3', 'Você sabe quais são povos e comunidades tradicionais brasileiros? Talvez indígenas e quilombolas sejam os primeiros que passam pela cabeça, mas, na verdade, além deles, existem 26 reconhecidos oficialmente e muitos outros que ainda não foram incluídos na legislação.

São pescadores artesanais, quebradeiras de coco babaçu, apanhadores de flores sempre-vivas, caatingueiros, extrativistas, para citar alguns, todos considerados culturalmente diferenciados, capazes de se reconhecerem entre si.

Para uma pesquisadora da UnB, essas populações consideram a como uma mãe, e há uma relação de reciprocidade com a natureza. Nesta troca, a natureza fornece “alimento, um lugar saudável para habitar, para ter água. E eles se responsabilizam por cuidar dela, por tirar dela apenas o suficiente para viver bem e respeitam o tempo de regeneração da própria natureza”, diz.', null, 'Disponível em: https://g1.globo.com (adaptado).'),
  ('7bec8040-9984-41b9-ac75-1bc0d3339dbb', 'e58b1ebb-68b2-4d37-a760-d8874ed771ec', '1', 'Comitê de Ajuda Humanitária da UEPB treina voluntários para atuar junto às vítimas de Palmares

Na manhã desta quinta-feira, cerca de 50 pessoas, entre alunos e professores da Universidade Estadual da Paraíba, participaram do 1º Treinamento de Equipe Multidisciplinar para Atuação em Situação de Emergência, oferecido pelo Comitê de Ajuda Humanitária, Social e da Saúde, criado recentemente pela Instituição.

A primeira atividade da equipe terá início já neste domingo, data em que viajarão para a cidade de Palmares (AL), onde permanecerão por uma semana, para oferecer apoio humanitário aos moradores daquela localidade, uma das tantas atingidas pelas chuvas e enchentes que assolaram os estados de Pernambuco e Alagoas nas últimas semanas.', null, 'Disponível em: http://www.uepb.edu.br/ (adaptado)'),
  ('368fdb21-2849-4fed-b456-16a3ba5fa00c', 'e58b1ebb-68b2-4d37-a760-d8874ed771ec', '2', 'TERREMOTO NO HAITI

Redes Sociais da Internet foram o principal meio de comunicação

Durante todo o dia de ontem, a Internet foi o principal meio usado pelo Haiti para se comunicar com o mundo. Mensagens ao exterior foram encaminhadas por estrangeiros no país e por moradores locais. Apesar da instabilidade na rede - os sistemas de luz e telefone também estavam intermitentes -, os sites de relacionamento foram usados para acalmar familiares e clamar por auxílio internacional. No Brasil, usuários do Twitter divulgaram a ação da ONG Viva Rio, que abriu uma conta para receber doações aos desabrigados no Haiti. (OT, com Agência Estado).', null, 'Disponível em: https://www.gazetadopovo.com.br/'),
  ('62d652de-ce82-48ce-830a-651ae0037ed2', 'e58b1ebb-68b2-4d37-a760-d8874ed771ec', '3', null, 'enem-ppl-2010-motivador-3.jpg', 'Disponível em: http://gcmandretavares.blogspot.com. Acesso em: 23 ago. 2010. '),
  ('4b1344a5-d8b2-40d0-96da-daba1802e1b6', '5eb9b76d-4890-4213-bb6d-46dda0c50093', '1', 'Fundado em 21 de janeiro de 1993, o Grupo Cultural AfroReggae foi criado para transformar a realidade de jovens moradores de favelas utilizando a educação, a arte e a cultura como instrumentos de inserção social. O embrião do projeto foi o jornal AfroReggae Notícias, cuja primeira edição circulou em agosto de 1992. O informativo — distribuído gratuitamente e sem anunciantes — logo se tornou um canal aberto para o debate de ideias e de problemas que afetam a vida de negros e pobres.

Desde então, o Grupo Cultural AfroReggae investe no potencial de jovens favelados, levando educação, cultura e arte a territórios marcados pela violência policial e pelo narcotráfico. Ao longo de seus 18 anos, o AfroReggae vem utilizando atividades artísticas, como percussão, circo, grafite, teatro e dança para tentar diminuir os abismos que separam negros e brancos, ricos e pobres, a favela e o asfalto, a fim de criar pontes de união entre os diferentes segmentos da sociedade.', null, 'Disponível em: http://www.afroreggae.org.br. Acesso em: 18 nov. 2010 (adaptado)'),
  ('a8a10ef5-505b-477b-a964-2daffc21fcf8', '5eb9b76d-4890-4213-bb6d-46dda0c50093', '2', null, 'enem-ppl-2011-motivador-2.jpg', 'isponível em: http://www.ibase.br. Acesso em: 18 nov. 2010.'),
  ('0cbfe2d5-d8be-404e-83a9-27d98db3b3b7', 'f9108be2-a88b-4a1c-8ccf-e62c8d6bafa4', '4', 'Carta da Amazônia 2021

Aos participantes da 26ª Conferência das Nações Unidas sobre Mudanças Climáticas

Não podia ser mais estratégico para nós, Povos Indígenas, Populações e Comunidades Tradicionais brasileiras, reafirmarmos a defesa da sociobiodiversidade amazônica neste momento em que o mundo volta a debater a crise climática na COP26. Uma crise que atinge, em todos os contextos, os viventes da Terra!

Nossos territórios protegidos e direitos respeitados são reivindicações dos movimentos sociais e ambientais brasileiros.

Não compactuamos com qualquer tentativa e estratégia baseada somente na lógica do mercado, com empresas que apoiam legislações ambientais que ameacem os nossos direitos e com mecanismos de financiamento que não condizem com nossa realidade dos nossos territórios.

Propomos o que temos de melhor: a experiência das nossas sociedades e culturas históricas, construídas com base em nossos saberes tradicionais e ancestrais, além do nosso profundo conhecimento da natureza.

Inovação, para nós, não pode resultar em processos que venham a ameaçar nossos territórios, nossas formas tradicionais e harmônicas de viver e produzir.

Amazônia, Brasil, 20 de Outubro de 2021.

Entidades signatárias: CNS; Coiab; Conaq; MIQCB; Coica; ANA Amazônia e Confrem.', null, 'Disponível em: https://s3.amazonaws.com (adaptado).'),
  ('c67d6432-c3ba-4863-8397-7fb00bb9bc38', '9270cfa8-bb76-4982-8576-6a8f4d010df2', '4', 'Trilha da Costura. 

Os imigrantes bolivianos, pelo último censo, são mais de 3 milhões, com população de aproximadamente 9,119 milhões de pessoas. A Bolívia em termos de IDH ocupa a posição de 114º de acordo com os parâmetros estabelecidos pela ONU. O país está no centro da América do Sul e é o mais pobre, sendo 70% da população considerada miserável. Os principais países para onde os bolivianos imigrantes dirigem-se são: Argentina, Brasil, Espanha e Estados Unidos. Assim sendo, este é o quadro social em que se encontra a maioria da população da Bolívia, estes dados já demonstram que as motivações do fluxo de imigração não são políticas, mas econômicas. Como a maioria da população tem baixa qualificação, os trabalhos artesanais, culturais, de campo e de costura são os de mais fácil acesso.', null, 'OLIVEIRA, R.T. Disponível em: http://www.ipea.gov.br. Acesso em: 19 jul. 2012 (adaptado).'),
  ('1a44cc9e-af0a-4abc-9891-0abfe42b4676', '1c8e26e3-eee5-48dc-a4be-f549d285af27', '1', null, 'enem-2009-motivador-1.jpg', 'Charge de Millôr Fernandes no Enem 2009 (Foto: Reprodução/Enem)'),
  ('70e9d1bd-4cd9-4f60-80b6-5a6ddf9e616a', '1c8e26e3-eee5-48dc-a4be-f549d285af27', '2', 'Andamos demais acomodados, todo mundo reclamando em voz baixa como se fosse errado indignar-se.

Sem ufanismo, porque dele estou cansada, sem dizer que este é um país rico, de gente boa e cordata, com natureza (a que sobrou) belíssima e generosa, sem fantasiar nem botar óculos cor-de-rosa, que o momento não permite, eu me pergunto o que anda acontecendo com a gente.

Tenho medo disso que nos tornamos ou em que estamos nos transformando, achando bonita a ignorância eloquente, engraçado o cinismo bem-vestido, interessante o banditismo arrojado, normal o abismo em cuja beira nos equilibramos – não malabaristas, mais palhaços.', null, 'LUFT, L. Ponto de vista. Veja. Ed. 1988, 27 dez 2006 (adaptado)'),
  ('1675c5c8-177d-486c-8dab-7817b147b4d2', '1c8e26e3-eee5-48dc-a4be-f549d285af27', '3', 'Qual é o efeito em nós do “eles são todos corruptos”?

As denúncias que assolam nosso cotidiano podem dar lugar a uma vontade de transformar o mundo só se nossa indignação não afetar o mundo inteiro. “Eles são TODOS corruptos” é um pensamento que serve apenas para “confirmar” a “integridade” de quem se indigna.

O lugar-comum sobre a corrupção generalizada não é uma armadilha para os corruptos: eles continuam iguais e livres, enquanto, fechados em casa, festejamos nossa esplendorosa retidão.

O dito lugar-comum é uma armadilha que amarra e imobiliza os mesmos que denunciam a imperfeição do mundo inteiro.', null, 'CALLIGARIS, C. A armadilha da corrupção. Disponível em: www1.folha.uol.com.br (adaptado)'),
  ('b94f3d33-b005-4f8f-862f-9ae1c7da8dd5', 'd8b0eb0d-8b99-4996-9921-65261e5f901f', '1', 'O que é trabalho escravo
Escravidão contemporânea é o trabalho degradante que envolve cerceamento da liberdade

A assinatura da Lei Áurea, em 13 de maio de 1888, representou o fim do direito de propriedade de uma pessoa sobre a outra, acabando com a possibilidade de possuir legalmente um escravo no Brasil. No entanto, persistiram situações que mantêm o trabalhador sem possibilidade de se desligar de seus patrões. Há fazendeiros que, para realizar derrubadas de matas nativas para formação de pastos, produzir carvão para a indústria siderúrgica, preparar o solo para plantio de sementes, entre outras atividades agropecuárias, contratam mão de obra utilizando os contratadores de empreitada, os chamados “gatos”. Eles aliciam os trabalhadores, servindo de fachada para que os fazendeiros não sejam responsabilizados pelo crime.

Trabalho escravo se configura pelo trabalho degradante aliado ao cerceamento da liberdade. Este segundo fator nem sempre é visível, uma vez que não mais se utilizam correntes para prender o homem à terra, mas sim ameaças físicas, terror psicológico ou mesmo as grandes distâncias que separam a propriedade da cidade mais próxima.', 'enem-2010-motivador-1.jpg', 'Disponível em: http://www.reporterbrasil.org.br. Acesso em: 02 set.2010 (fragmento).'),
  ('5a0a9e84-d138-4b9b-b819-dce130cf1e8e', 'd8b0eb0d-8b99-4996-9921-65261e5f901f', '2', 'O futuro do trabalho

Esqueça os escritórios, os salários fixos e a aposentadoria. Em 2020, você trabalhará em casa, seu chefe terá menos de 30 anos e será uma mulher.

Felizmente, nunca houve tantas ferramentas disponíveis para mudar o modo como trabalhamos e, consequentemente, como vivemos. E as transformações estão acontecendo. A crise despedaçou companhias gigantes tidas até então como modelos de administração. Em vez de grandes conglomerados, o futuro será povoado de empresas menores reunidas em torno de projetos em comum. Os próximos anos também vão consolidar mudanças que vêm acontecendo há algum tempo: a busca pela qualidade de vida, a preocupação com o meio ambiente, e a vontade de nos realizarmos como pessoas também em nossos trabalhos. “Falamos tanto em desperdício de talentos?”, diz o filósofo e ensaísta suíço Alain de Botton em seu novo livro The Pleasures and Sorrows of Works (Os prazeres e as dores do trabalho, ainda inédito no Brasil).', 'enem-2010-motivador-2.jpg', 'Disponível em: http://revistagalileu.globo.com. Acesso em: 02 set. 2010 (fragmento)'),
  ('4346be64-db35-43b2-9fc2-6c32f62d7733', '4b47ec2f-6a2b-4e82-9baf-f77a0ecba90e', '1', 'Liberdade em fio

A ONU acaba de declarar o acesso à rede um direito fundamental do ser humano – assim como saúde, moradia e educação. No mundo todo, pessoas começam a abrir seus sinais privados de wi-fi, organizações e governos se mobilizam para expandir a rede para espaços públicos e regiões onde ela ainda não chega, com acesso livre e gratuito.', null, 'ROSA, G.; SANTOS, P. Galileu. Nº 240, jul. 2011 (fragmento)'),
  ('eb2626c3-3be6-445b-b9a7-308f4cbf84dd', '4b47ec2f-6a2b-4e82-9baf-f77a0ecba90e', '2', 'A internet tem ouvidos e memória

Uma pesquisa da consultoria Forrester Research revela que, nos Estados Unidos, a população já passou mais tempo conectada à internet do que em frente à televisão. Os hábitos estão mudando. No Brasil, as pessoas já gastam cerca de 20% de seu tempo on-line em redes sociais. A grande maioria dos internautas (72%, de acordo com o Ibope Mídia) pretende criar, acessar e manter um perfil em rede. “Faz parte da própria socialização do indivíduo do século XXI estar numa rede social. Não estar equivale a não ter uma identidade ou um número de telefone no passado”, acredita Alessandro Barbosa Lima, CEO da e.Life, empresa de monitoração e análise de mídias.

As redes sociais são ótimas para disseminar ideias, tornar alguém popular e também arruinar reputações. Um dos maiores desafios dos usuários de internet é saber ponderar o que se publica nela. Especialistas recomendam que não se deve publicar o que não se fala em público, pois a internet é um ambiente social e, ao contrário do que se pensa, a rede não acoberta anonimato, uma vez que mesmo quem se esconde atrás de um pseudônimo pode ser rastreado e identificado. Aqueles que, por impulso, se exaltam e cometem gafes podem pagar caro.', null, 'Disponível em: http://www.terra.com.br. Acesso em: 30 jun. 2011 (adaptado)'),
  ('4dd6b0a8-4266-4811-b581-8365c4f8b8a9', '4b47ec2f-6a2b-4e82-9baf-f77a0ecba90e', '3', null, 'enem-2011-motivador-3.jpg', 'DAHMER, A. Disponível em: http://malvados.wordpress.com. Acesso em: 30 jun. 2011.'),
  ('78838bd7-7f31-4e5d-9adc-ed59e4b8c8bc', 'd3fd122f-a272-40a5-9172-56b4bc77f22c', '1', 'Qual o objetivo da “Lei Seca ao volante”? 

De acordo com a Associação Brasileira de Medicina de Tráfego (Abramet), a utilização de bebidas alcoólicas é responsável por 30% dos acidentes de trânsito. E metade das mortes, segundo o Ministério da Saúde, está relacionada ao uso do álcool por motoristas. Diante deste cenário preocupante, a Lei 11.705/2008 surgiu com uma enorme missão: alertar a sociedade para os perigos do álcool associado à direção. Para estancar a tendência de crescimento de mortes no trânsito, era necessária uma ação enérgica. E coube ao Governo Federal o primeiro passo, desde a proposta da nova legislação à aquisição de milhares de etilômetros. Mas para que todos ganhem, é indispensável a participação de estados, municípios e sociedade em geral. Porque para atingir o bem comum, o desafio deve ser de todos.', null, 'Disponível em: www.dprf.gov.br. Acesso em: 20 jun. 2013.'),
  ('ae846480-6db3-4068-8142-116c8247480f', 'd3fd122f-a272-40a5-9172-56b4bc77f22c', '2', null, 'enem-2013-motivador-2.png', 'Disponível em: www.brasil.gov.br. Acesso em: 20 jun. 2013.'),
  ('1ebc6e3d-7b4b-490a-bc99-ea6fc8e62756', 'd3fd122f-a272-40a5-9172-56b4bc77f22c', '3', null, 'enem-2013-motivador-3.png', 'Disponível em: www.operacaoleisecarj.rj.gov.br. Acesso em: 20 jun. 2013 (adaptado).'),
  ('bf09352d-059a-4805-99e2-196e7738486f', 'd3fd122f-a272-40a5-9172-56b4bc77f22c', '4', 'Repulsão magnética a beber e dirigir. 

A lei da física que comprova que dois polos opostos se atraem em um campo magnético é um dos conceitos mais populares desse ramo do conhecimento. Tulipas de chope e bolachas de papelão não servem, em condições normais, como objetos de experimento para confirmar essa proposta. A ideia de uma agência de comunicação em Belo Horizonte foi bem simples. Ímãs foram inseridos em bolachas utilizadas para descansar os copos, de forma imperceptível para o consumidor. Em cada lado, há uma opção para o cliente: dirigir ou chamar um táxi depois de beber. Ao mesmo tempo, tulipas de chope também receberam pequenos pedaços de metal mascarados com uma pequena rodela de papel na base do copo. Durante um fim de semana, todas as bebidas servidas passaram a pregar uma peça no cliente. Ao tentar descansar seu copo com a opção dirigir virada para cima, os ímãs apresentavam a mesma polaridade e, portanto, causando repulsão, fazendo com que o descanso fugisse do copo; se estivesse virada mostrando o lado com o desenho de um táxi, ela rapidamente grudava na base do copo. A ideia surgiu da necessidade de passar a mensagem de uma forma leve e no exato momento do consumo.', null, 'Disponível em: www.operacaoleisecarj.rj.gov.br. Acesso em: 20 jun. 2013 (adaptado).'),
  ('5a818a9b-ad7e-465e-8fa2-54533713c83c', '7163e3f0-adf0-42c1-821b-7e608973a459', '1', null, 'enem-ppl-2009-motivador-1.jpg', 'Disponível em: AMARAL, Tarsila do. A Família. 1925. Óleo sobre tela, 79 cm X 101,5 cm. Coleção Torquato Sabóia Pessoa, SP.'),
  ('334bfa2c-2ed3-47e7-9d90-cde8082dbaf3', '7163e3f0-adf0-42c1-821b-7e608973a459', '2', 'O desenvolvimento de instituições modernas do Estado e do mercado abarca, em parte, as antigas funções da família, restringindo a esfera de atuação desta às dimensões da afetividade e da reprodução da vida, em seus aspectos biológico e culturais. Por essa razão, é importante refletir sobre como o Estado, por meio de seu papel regulador e de promotor de políticas públicas, deve assumir responsabilidades perante os indivíduos, as famílias e o bem-estar coletivo.', null, 'Disponível em: http://www.abep.nepo.unicamp.br.'),
  ('6c3b78a1-1f14-4851-a474-1d144958408a', '7163e3f0-adf0-42c1-821b-7e608973a459', '3', 'Lidar com as famílias, hoje, é lidar com a diversidade; famílias intactas, famílias em processo de separação, famílias monoparentais, famílias reconstruídas, famílias constituídas de casais homossexuais, famílias constituídas de filhos adotivos, famílias constituídas por meio das novas técnicas de reprodução.
A família intacta, tal qual nos acostumamos a pensar como sendo o modelo de família, é, hoje em dia, uma das várias formas de se viver a família.
A multiplicidade "ser família", hoje, cria um hiato na geração que aprendeu o "ser família" de acordo com determinadas características e sua concretização na prática. Talvez só a geração dos filhos saiba desenvolver a maneira de denominar tal realidad', null, 'Disponível em: http://www.tvebrasil.com.br.'),
  ('f56f1f29-7c0f-4ffa-84f4-29e43353c9c9', '5eb9b76d-4890-4213-bb6d-46dda0c50093', '3', 'Betinho: uma trajetória de luta

Herbert José de Souza, o Betinho, buscou a vida de forma intensa para si e para os outros, particularmente para os excluídos da sociedade. Seu humor e sua ironia juntavam-se a uma forte indignação diante da mínima injustiça.

Ele afirmava que a democracia não é um modelo ou uma estrutura acabada; é algo que constantemente deve ser sonhado, imaginado ou recriado. A busca de ser livre, igual, diverso, solidário e participante é um princípio que deve fermentar nosso constante sonhar e imaginar a democracia como guia de intervenção cidadã. ', null, 'GRZYBOWSKI, C. Disponível em: http://www.comitebetinho.org.br. Acesso em: 18 nov. 2010 (adaptado).'),
  ('60be4f7e-83e5-43c1-9e28-f3015403b787', '88cd6b33-22ce-4bf7-8eb1-c4cedbfc40b8', '1', 'Nasce um grande movimento

A associação dos Funcionários de Bancos de São Paulo teve seu estatuto aprovado em 16 de abril de 1923, em assembleia da qual participaram 84 bancários. A preocupação inicial era credenciar os bancários à entidade e criar uma identidade da categoria, até então integrada aos comerciários. Menos de 10 anos depois aconteceu a primeira greve de bancários da história, iniciada em Santos, em 18 de abril de 1932. Eram os funcionários do Banespa que reivindicavam melhorias salariais e das condições sanitárias - havia grande incidência de tuberculose à época. Essa greve foi vitoriosa; entretanto, a conquista que marcou a década de 30 foi a redução da jornada de trabalho para seis horas, em novembro de 1933. A Associação passou a chamar-se Sindicato dos Bancários de São Paulo.', 'enem-ppl-2012-motivador-1.jpg', 'Disponível em: https://spbancarios.com.br/'),
  ('972c763c-fe89-442f-8c91-d99c4739164d', '88cd6b33-22ce-4bf7-8eb1-c4cedbfc40b8', '2', 'Corinthians Campeão da Libertadores — Jorge Henrique: ‘O grupo é maravilhoso’

Contendo as lágrimas após o término da final da Libertadores, Jorge Henrique falou primeiro sobre a Fiel. “Eu sei que essa nação me ama pelo que faço em campo”, disse o atacante emocionado.

Mostrando a união, o camisa 23 elogiou a equipe. “O grupo é maravilhoso, humilde, não tem estrela. Fomos conquistando nosso espaço”, disse o corinthiano.', null, 'Disponível em: www.mennel.com.br. Acesso em: 19 jul. 2012 (adaptado).'),
  ('d5d1881f-1f53-4183-9106-b968e0076e8f', '88cd6b33-22ce-4bf7-8eb1-c4cedbfc40b8', '3', 'Marcha das vadias

A 2ª edição brasileira da Marcha das Vadias aconteceu simultaneamente em 14 cidades do país, entre elas São Paulo (SP), Florianópolis (SC), Rio de Janeiro (RJ), Belo Horizonte (MG), Brasília (DF), Recife (PE), Salvador (BA) e Natal (RN). Além de chamar a atenção aos diversos tipos de violência sofridos pelas mulheres — verbal, física ou sexual —, a mobilização pretende combater a responsabilização das vítimas pela violência sofrida e ressaltar os direitos do sexo feminino.

A manifestação é inspirada no movimento mundial intitulado “Slut Walk”, criado em abril do ano passado, após um oficial da polícia de Toronto, no Canadá, dizer que, para evitar estupros, as mulheres deveriam deixar de se “vestir como vadias”. ', null, 'Disponível em: http://noticias.uol.com.br. Acesso em: 19 jul. 2012 (adaptado)'),
  ('f447e312-594c-4c78-8e57-f956e770b2ad', 'b592af2b-c5bb-4525-9bc4-fa63a0fcbe22', '1', 'Cooperativas e desenvolvimento sustentável A Assembléia Geral das Nações Unidas proclamou 2012 o Ano Internacional das Cooperativas, como reconhecimento do papel fundamental das Cooperativas na promoção do desenvolvimento sócio-econômico de centenas de milhões de pessoas em todo o mundo.

Com este propósito, a Assembléia Geral da ONU apela para a comunidade internacional a fim de que medidas sejam tomadas para a criação de um ambiente favorável e capacitante para o fomento à instalação de cooperativas, objetivando a promoção da conscientização dos povos em relação às importantes contribuições das cooperativas para a geração de empregos e para a consequente melhoria qualitativa de vida dos povos.', null, 'Disponível em: www.peaunesco.com.br. Acesso em: 20 jun. 2013.'),
  ('24b5c75c-1052-4197-ad87-3b596e498a84', 'b592af2b-c5bb-4525-9bc4-fa63a0fcbe22', '2', null, 'enem-ppl-2013-motivador-2.jpg', 'Disponível em: www.peaunesco.com.br. Acesso em: 20 jun. 2013.'),
  ('95610458-8764-4450-a797-f999f9c7546d', 'b592af2b-c5bb-4525-9bc4-fa63a0fcbe22', '3', null, 'enem-ppl-2013-motivador-3.jpg', 'Disponível em: www.doeseulixo.org.br. Acesso em: 20 jun. 2013.'),
  ('520ebce5-24bb-4fa0-869a-6f893572b5b0', 'b592af2b-c5bb-4525-9bc4-fa63a0fcbe22', '4', '“Porque nós somos os médicos do planeta, o planeta está doente e o ser humano está adoecendo cada vez mais. Quanto menos ele trata o lixo, mais ele adoece o planeta. E nós estamos aqui fazendo um trabalho digno. De fazer com que aquelas pessoas que ainda não têm consciência, bem, vamos esperar que elas tenham, mas enquanto isso nós vamos fazendo esse trabalho”. 

Marli, membro de uma cooperativa de catadores de lixo instalada no centro de São Paulo', null, 'Disponível em: http://g1.globo.com. Acesso em: 20 jun. 2013 (adaptado).'),
  ('00e27506-9fbd-4dad-a84e-b3b8350b0496', 'f7b84362-7fa2-43f2-adcc-515fbfdd2e24', '1', 'Segundo o MC Daniel de Souza, a origem do “rolezinho” remete aos chamados encontros de admiradores, em que fãs dos cantores de funk iam aos shoppings para encontrar os ídolos. “Antes do ‘rolezinho’ tinha o encontro de admiradores, que era com os famosinhos das redes sociais, que faziam o seu encontro e reuniam o povo no shopping”, declarou. “É o único lugar que todo mundo conhece e é público”. O jovem acredita que os encontros de admiradores cresceram e se tornaram os “rolezinhos” de hoje, atraindo também pessoas que aproveitam a situação para causar tumulto.', null, 'ANTONIO, T. Disponível em: http://memoria.ebc.com.br. Acesso em: 16 jun. 2014 (adaptado)'),
  ('d429814c-289d-4dec-87f2-47d7f061ea72', 'f7b84362-7fa2-43f2-adcc-515fbfdd2e24', '2', null, 'enem-ppl-2014-motivador-2.jpg', 'Disponível em: http://altamiroborges.blogspot.com.br. Acesso em: 16 jun. 2014.'),
  ('5acc6122-3393-467f-9f82-368b7c713718', 'f7b84362-7fa2-43f2-adcc-515fbfdd2e24', '3', 'O funk da ostentação, surgido na Baixada Santista e Região Metropolitana de São Paulo nos últimos anos, evoca o consumo, o luxo, o dinheiro e o prazer que tudo isso dá. Em seus clipes, os MCs aparecem com correntes e anéis de ouro, vestidos com roupas de grife, em carros caros, cercado por mulheres. Diferentemente do núcleo duro do hip hop paulista dos anos 80 e 90, que negava o sistema, e também do movimento de literatura periférica e marginal que, no início dos anos 2000, defendia que, se é para consumir, que se comprem as marcas produzidas pela periferia, para a periferia, o funk da ostentação coloca os jovens, ainda que para a maioria só pelo imaginário, em cenários até então reservados para a juventude branca das classes média e alta. Esta, talvez, seja a sua transgressão. Em seus clipes, os MCs têm vida de rico, com todos os signos dos ricos.

Esta exaltação do luxo e do consumo, interpretada como adesão ao sistema, tornou o funk da ostentação desconfortável para uma parcela dos intelectuais brasileiros e mesmo para parte das lideranças culturais das periferias de São Paulo. Agora, os rolezinhos – e a repressão que se seguiu a eles – deram a esta vertente do funk uma marca de insurgência. Ao ocupar os shoppings, a juventude pobre e negra das periferias não estava apenas se apropriando dos valores simbólicos, como já fazia pelas letras do funk da ostentação, mas também dos espaços físicos, o que marca uma diferença.', null, 'BRUM, E. Disponível em: http://arquivo.geledes.org.br. Acesso em: 16 jun. 2014 (fragmento)'),
  ('2e120fc8-59ab-4c80-87cf-01096a2e5320', '5090fc5c-c69b-4499-b813-30b51ff9c81a', '3', 'A escolha profissional passava necessariamente pela ideia de frequentar um curso de qualidade. Este curso dava uma excelente cultura geral e preparo adequado para exercer uma profissão que era reputada como digna e prestigiada. E, nesse caso, independentemente que fosse ela exercida por homens ou por mulheres. A figura da mulher que lecionava era bem aceita e apontada às moças como exemplo de honestidade e ideal a ser seguido. O mesmo acontecia com o professor. A família tinha a figura da professora e do professor em grande consideração. Estes detinham um prestígio social que estava em claro desacordo com a remuneração salarial percebida. Eles desfrutavam um prestígio advindo do saber, e não do poder aquisitivo.', null, 'ALMEIDA, J. S. D. Mulher e educação: a paixão pelo possível. São Paulo: Unesp, 1998 (adaptado).'),
  ('9a6c4113-8c55-4f69-9dff-8dd9798e13a8', '5090fc5c-c69b-4499-b813-30b51ff9c81a', '4', null, 'enem-ppl-2015-motivador-4.jpg', 'Disponível em: http://www.sinprodf.org.br. Acesso em: 26 jun.2015.'),
  ('46978bdb-51f7-447d-af90-4706d5a48368', 'e82694a8-9a7b-49dd-985b-08a77f9e01a8', '1', 'Um terço dos alimentos produzidos no mundo é desperdiçado a cada ano - junto com toda a energia, mão de obra, água e produtos químicos envolvidos em sua produção. O Brasil tem 3,4 milhões de brasileiros que estão em situação de insegurança alimentar, o que representa 1,7% da população. Segundo relatório da FAO (Organização das Nações Unidas para a Alimentação e Agricultura), de 2013, 805 milhões de pessoas, ou seja, 1 em cada 9 sofre de fome no mundo.', null, 'Disponível em: www.bancodealimentos.org.br'),
  ('dc443a2d-0f52-4bb1-9ac2-fa4e4499178d', 'e82694a8-9a7b-49dd-985b-08a77f9e01a8', '2', 'O desperdício de alimentos no Brasil chega a 40 mil toneladas por dia, segundo pesquisa da Empresa Brasileira de Pesquisa Agropecuária (Embrapa). Anualmente, a quantia acumulada é suficiente para alimentar cerca de 19 milhões de pessoas diariamente.', null, 'Disponível em: www.redebrasilatual.com.br'),
  ('9e0d9900-0607-462b-a449-8a36c79e745b', 'e82694a8-9a7b-49dd-985b-08a77f9e01a8', '3', null, 'enem-ppl-2016-motivador-3.jpg', 'Disponível em: http://www.infograficos.oglobo.globo.com. Acesso em: 24 de jun. 2016.'),
  ('8c0413ee-8b12-43cb-8a78-f64ebadb446e', 'e82694a8-9a7b-49dd-985b-08a77f9e01a8', '4', 'O desperdício de alimentos nas sociedades ricas resulta de uma combinação entre o comportamento do consumidor e a falta de comunicação ao longo da cadeia de abastecimento. Os consumidores não conseguem planejar suas compras de forma eficaz e, por isso, compram em excesso ou exageram no cumprimento das datas de validade dos produtos.  Por outro lado, os padrões estéticos e de qualidade levam os distribuidores a rejeitar grandes quantidades de alimentos perfeitamente comestíveis. Nos países em desenvolvimento, as grandes perdas pós-colheita, ainda na fase inicial da cadeia alimentar, são o principal problema.', null, 'Disponível em: www.onuverde.org.br'),
  ('3fa4cf3e-78f5-4667-8023-977089eaa6f7', '4a06b0f1-f1af-429c-af6c-4622a2a23fb2', '1', 'A beleza parece caminhar em uma linha tênue entre as escolhas do indivíduo e a imposição coletiva. Se, por um lado, cada um pode buscar a beleza da maneira que considerar melhor para si, por outro, cuidar da beleza torna-se um imperativo. Modelos funcionam como fonte de comparação social e a exposição às imagens idealizadas da mídia tem como efeito uma redução no nível de satisfação dos indivíduos com relação à própria imagem. Este processo de comparação social também influencia fortemente a autoestima do indivíduo. A percepção de uma discrepância acentuada entre o eu real e o eu ideal gera ansiedade e sentimento de insatisfação com relação ao seu autoconceito e, consequentemente, uma redução na sua autoestima. Na tentativa de atingir um ideal estético socialmente aceito, muitos se dedicam a uma luta incansável para esculpir o corpo perfeito e aproximar-se de um padrão de beleza.', null, 'FONTES, O. A.; BORELLI, F. C.; CASOTTI, L. M. Como ser homem e ser belo? Um estudo exploratório sobre a relação entre masculinidade e o consumo de beleza.Disponível em: http://seer.ufrgs.br. Acesso em: 22 jun. 2015 (adaptado).'),
  ('d138de5f-4b95-4249-b575-b3763abbbd78', '4a06b0f1-f1af-429c-af6c-4622a2a23fb2', '2', null, 'enem-ppl-2017-motivador-2.jpg', 'ROSSETTI, C. Disponível em: www.carolrossetti.com.br. Acesso em: 21 jul. 017.'),
  ('836d36f3-6115-4b4b-b066-4edf3c875f71', '4a06b0f1-f1af-429c-af6c-4622a2a23fb2', '3', 'Os transtornos alimentares mais relevantes em nosso contexto sociocultural são a anorexia e a bulimia nervosas. A anorexia nervosa se  caracteriza pelo pavor descabido e inexplicável que a pessoa tem de engordar, com grave distorção da sua imagem corporal. Para atingir esse padrão de “beleza” inatingível, o anoréxico se submete a regimes alimentares bastante rigorosos e agressivos. Já a bulimia nervosa se caracteriza pela ingestão compulsiva e exagerada de alimentos, geralmente muito calóricos, seguida por um enorme sentimento de culpa em função dos “excessos” cometidos. Não podemos perder de vista que a formação da autoimagem corporal de cada pessoa está fortemente influenciada pela maneira como a sociedade “impõe” o que é ter um corpo esteticamente apreciável.', null, 'SILVA, A. B. B. Bullying: mentes perigosas nas escolas.Rio de Janeiro: Objetiva, 2010 (adaptado).'),
  ('64a24ac9-079c-4e75-bd3e-71e3f53cd1a1', 'd7dbaeb5-9331-432a-8454-0e3aa4031623', '1', null, 'enem-ppl-2018-motivador-1.jpg', 'isponível em: https://g1.globo.com. Acesso em: 7 maio 2018 (adaptado).'),
  ('4a9db3a0-77f7-40b6-a389-87ea3a403e9d', 'd7dbaeb5-9331-432a-8454-0e3aa4031623', '2', 'Moedas sociais circulam por todo o Brasil e impulsionam economia das comunidades Engana-se quem pensa que o Real é a única moeda em circulação no Brasil. Além dele, existem centenas de outras, chamadas de moedas sociais, já muito usadas em diversas regiões do país. As moedas sociais estão ligadas a bancos comunitários. Elas são consideradas complementares à moeda oficial brasileira e, em geral, são lastreadas pelo Real. Hoje, as mais de cem moedas sociais em circulação no Brasil movimentam mais de R$ 6 milhões por ano, seja em crédito produtivo, seja em meio circulante físico. Esses bancos atuam onde os bancos tradicionais não entram.', null, 'Disponível em: www.conexaoplaneta.com.br. Acesso em: 7 maio 2018 (adaptado)'),
  ('9d2bf847-08c0-4a38-8527-1b39a6fba1ec', 'd7dbaeb5-9331-432a-8454-0e3aa4031623', '3', 'Desde 2011, os Xavante da Aldeia Marãiwatsédé fazem parte da Rede de Sementes do Xingu. A aldeia Ripá, da mesma etnia, se juntou a eles no trabalho de coleta e comercialização de sementes florestais para a recuperação de áreas degradadas. Além de ser uma importante alternativa econômica para os Xavante, a atuação na produção de sementes efetiva caminhos para o mapeamento participativo dos territórios e integra valorização da cultura tradicional com novas oportunidades para os jovens.', 'enem-ppl-2018-motivador-3.jpg', 'Disponível em: terramirim.org.br (adaptado)'),
  ('2265e3d5-ab56-4006-8435-d667645a0946', 'd7dbaeb5-9331-432a-8454-0e3aa4031623', '4', 'P.S.O.: Qual seria a importância principal da economia solidária na sociedade brasileira atual?

Paul Singer: O trabalho é uma forma de aprender, de crescer, de amadurecer, e essas oportunidades a economia solidária oferece a todos, sem distinção. [...] Os trabalhadores não têm um salário assegurado no fim do mês, que é uma das conquistas importantes dos trabalhadores no sistema capitalista, no qual eles não participam dos lucros e tampouco dos riscos. Agora, trabalhando em sua própria cooperativa, eles são proprietários de tudo o que é produzido, mas também os prejuízos são deles.', null, 'SINGER, Paul. Economia Solidária. [Jan./Abr. 2008] São Paulo: Estudos Avançados. v. 22, n. 62. Entrevista concedida a Paulo de Salles Oliveira'),
  ('f9760e07-cea7-4439-8749-3d6c3dd0cfa5', '1a4d3b3f-633b-4634-ab54-3beb3bd98dee', '1', null, 'enem-ppl-2020-motivador-1.jpg', 'Disponível em: https://www.instagram.com/akapoeta/'),
  ('60439afc-2178-421c-9cf5-8a8a525a6697', '1a4d3b3f-633b-4634-ab54-3beb3bd98dee', '2', 'Penso que a nossa geração esteja repleta de pessoas empáticas. Há muitos que sabem sentir a dor do mundo e que primam dor preencher a nossa atmosfera psíquica com as flores da gentileza e o perfume da gratidão. Esses seres, embora raramente tenham holofotes sobre si, são os verdadeiramente ricos e poderosos, pois são os seus gestos anônimos, as suas preces silenciosas e seus pensamentos de paz que espalham centelhas de esperança por toda a Terra. Mas é inegável que muitos ainda não tenham compreendido que as maiores mazelas do mundo se dão pela falta de empatia dos homens. Por não saber "ser o outro", o homem furta, rouba, violenta. O homem achincalha a fé alheia, o sonho alheio. O homem esvazia o homem. O homem condena povos inteiros, comunidades inteiras à miséria, roubando-lhes as condições necessárias, de modo que não possam sequer enxergar a própria indignidade. É a falta de empatia que contamina o mundo com a praga do imediatismo, do consumismo, do uso indiscriminado de recursos naturais. A falta de empatia faz com que desumanizemos o outro e, com isso, nos tornemos menos humanos, mais egoístas, mais individualistas, mais competitivos e mais insanos.', null, 'Disponível em: https://www.revistapazes.com/ (adaptado)'),
  ('858e071c-828c-45ce-97b3-b404942f4fa7', '1a4d3b3f-633b-4634-ab54-3beb3bd98dee', '3', null, 'enem-ppl-2020-motivador-3.jpg', 'Disponível em: http://www.generonumero.media/'),
  ('0d81979a-b2ae-4a81-9219-feba225e707d', '846cc34e-c7c4-4f14-8dc9-94382a68ce82', '1', 'Os impactos negativos do exagero da tecnologia não ficam restritos aos aspectos comportamentais e emocionais. Há também a ameaça do sedentarismo. Uma pesquisa da Universidade Estadual de Campinas (Unicamp) avaliou os hábitos de 21 voluntários com idade entre 8 e 12 anos e constatou que 14 deles não praticavam nenhuma atividade física. Na sala de aula a história também desanda. “A luz emitida pelo visor reduz a produção de melatonina, hormônio indutor do sono”, observa uma das pesquisadoras responsáveis. Sem a substância, fica difícil adormecer e há maior risco de despertar na madrugada. “O sono de má qualidade interfere na concretização das memórias e do aprendizado do dia”, aponta uma neuropediatra.', null, 'Disponível em: https://saude.abril.com.br. Acesso em: 3 de jun. 2019 (adaptado).'),
  ('d7ca5446-f8d6-4767-912b-44742eb75e29', '846cc34e-c7c4-4f14-8dc9-94382a68ce82', '2', 'Riscos e benefícios das novas tecnologias para crianças

Segundo a Academia Americana de Pediatria (AAP), há claras evidências de que as mídias digitais contribuem substancialmente para diferentes problemas de saúde, como a obesidade e comportamentos agressivos e/ou alienados. Por outro lado, a AAP reconhece os benefícios da tecnologia na aprendizagem e nos relacionamentos sociais, a partir da interatividade possibilitada pelos diferentes dispositivos de mídia digital. As novas tecnologias de comunicação alteraram a forma de acesso e armazenamento da memória, pois, através de imagens, sons e movimentos apresentados nos dispositivos eletrônicos de comunicação é possível fixar conteúdos, armazenar sentimentos, aprendizagens e lembranças que não necessariamente foram vivenciadas presencialmente pelos espectadores. As mídias digitais propiciam experiências culturais através de interações diversificadas, permitindo às crianças apropriarem-se do conteúdo e da comunicação baseados em suas necessidades, motivações e interesse.', null, ' Não disponível'),
  ('4bc3b4f4-3714-4cc2-8366-9ae8d8f2ce0b', '846cc34e-c7c4-4f14-8dc9-94382a68ce82', '3', null, 'enem-2019-motivador-3.jpg', 'Não disponível'),
  ('225dadd4-1664-4a91-b833-e6e3d274a252', '7bfdf552-60e6-420d-a951-f57ad080b0c1', '1', 'Vinda de uma família abastada, viúva e irmã de militares, Anna Nery foi contratada como enfermeira para auxiliar o corpo de saúde do Exército Brasileiro e permaneceu atendendo feridos e enfermos durante o conflito da Guerra do Paraguai, até 1870. Na época, doenças ameaçavam a saúde dos soldados, mas Anna conseguiu transformar a realidade sanitária dos locais onde trabalhava,  impondo condições mínimas de higiene para que essas doenças não se alastrassem e para que as pessoas fossem tratadas com segurança. A sua história está documentada no Museu Nacional da Enfermagem, fundado em 2010. Anna Nery é semelhante à de Florence Nightingale, a inglesa que consolidou seu trabalho de cuidado na Guerra da Crimeia e fundando, assim, a enfermagem no século XIX.', null, 'Disponível em: https://oglobo.globo.com. Acesso em 2 jul. 2021 (adaptado).'),
  ('17511839-52df-405a-9d85-acaed2bb6a06', '7bfdf552-60e6-420d-a951-f57ad080b0c1', '2', 'Adriana Melo foi pioneira na identificação da relação da zika com microcefalia. Após cinco anos do surto no país, ela ajuda famílias com um projeto singular na Paraíba – e diz que ainda há muito a aprender sobre a doença.

“Infelizmente, o interesse internacional em pesquisa diminuiu muito”, reclama Melo, “porque o zika não chegou ao mundo rico, não chegou à Europa e aos Estados Unidos. Perdeu-se totalmente o interesse pelo assunto.” Para ela, é uma negligência, uma vez que o vírus zika continua causando novos casos de microcefalia em crianças.', null, 'Disponível em: https://oglobo.globo.com. Acesso em 22 jul. 2021.'),
  ('77776585-c331-4917-9f0d-2d58b2003059', '7bfdf552-60e6-420d-a951-f57ad080b0c1', '3', 'A vida de uma médica entre seis hospitais e três filhos durante a pandemia
Entro em casa pela porta dos fundos, higienizo as mãos com álcool gel. Tiro a roupa na lavanderia, coloco direto na máquina de lavar. Sigo para o banho. Agora essa é minha rotina. No entanto, a pior parte é a de não chegar perto das crianças.

Saindo do banho, vejo que há duas ligações não atendidas. Retorno a primeira: uma amiga, cardiologista, conta que não vai conseguir voltar ao hospital para atender um paciente. Ela já vinha apresentando um quadro de moleza desde sábado, mas como nós, médicos, estamos habituados a fazer, ignorou os sintomas por serem leves. Tirou um cochilo hoje à tarde e acordou com febre. Ela me contou que atendeu um paciente, quatro dias atrás, que estava com febre depois de voltar de uma viagem (ele fez o teste e hoje recebeu o resultado, ou seja, positivo). Até perceber o risco, o contato já havia acontecido. Pedi para ela fazer exame para Covid-19 e ficar em isolamento domiciliar.', null, 'Disponível em: https://oglobo.globo.com. Acesso em 22 jul. 2021.'),
  ('55d7b5c0-310b-46c8-b550-f7de06a580d5', 'a16ef606-d9f3-452a-a735-f8b28f28a973', '1', 'Fragmento do livro Geografia da Fome, de Josué de Castro, publicado em 1946

A alimentação do brasileiro tem-se revelado, à luz dos inquéritos sociais realizados, com qualidades nutritivas bem precárias, apresentando, nas diferentes regiões do país, padrões dietéticos mais ou menos incompletos e desarmônicos. Numas regiões, os erros e defeitos são mais graves, e vive-se num estado de fome crônica; noutras, são mais discretos, e tem-se a subnutrição. Procurando investigar as causas fundamentais dessa alimentação em regra tão defeituosa e que tem pesado tão duramente na evolução econômico-social do povo, chega-se à conclusão de que elas são mais produto de fatores socioculturais do que de fatores de natureza geográfica.', null, 'CASTRO, J. Geografia da Fome. 9ª ed. Rio de Janeiro: Civilização Brasileira, 2008 (adaptado).'),
  ('5354f787-7791-4c07-9ee2-700c94a95916', 'a16ef606-d9f3-452a-a735-f8b28f28a973', '2', 'O sociólogo Herbert de Souza, o Betinho, imortalizado na música de Aldir Blanc e João Bosco, pela voz de Elis Regina, como o “irmão do Henfil”, mobilizou o país na luta pela ética na política, pelo combate à fome e à miséria e na defesa da vida, na década de 1990.

Quem tem fome tem pressa. A frase era o lema de Betinho durante a campanha da Ação da Cidadania contra a Fome, a Miséria, e pela Vida, que colocou o combate à fome no foco das manifestações populares e das políticas públicas.', null, 'Disponível em: https://agenciabrasil.ebc.com.br. Acesso em: 15 jun. 2022 (adaptado).'),
  ('ec06b1d4-8bd8-466a-9c3c-451bedcf5ed2', 'a16ef606-d9f3-452a-a735-f8b28f28a973', '3', null, 'enem-ppl-2022-motivador-3.jpg', 'Disponível em: https://atalmineira.com. Acesso em: 15 jun. 2022'),
  ('95718e77-8c12-4c6d-aedf-a1e0f5999d81', 'a16ef606-d9f3-452a-a735-f8b28f28a973', '4', 'Atualmente, 33 milhões de pessoas passam fome no país, segundo resultado de uma nova pesquisa sobre o tema divulgada em junho de 2022. Em 1993, eram 32 milhões de pessoas nessa situação, segundo dados semelhantes do Ipea (Instituto de Pesquisa Econômica Aplicada). Disponível', null, 'Disponível em: https://www1.folha.uol.com.br. Acesso em: 15 jun. 2022 (adaptado).'),
  ('68153353-2831-4595-a9bd-8f0986cf89de', 'e8107cbf-03ca-4d8c-af98-096ce82ebdd5', '1', 'O Decreto n. 7 053, de 23 de dezembro de 2009, institui a Política Nacional para a População em Situação de Rua e seu Comitê Intersetorial de Acompanhamento e Monitoramento, e dá outras providências.

Parágrafo único. Para fins deste Decreto, considera-se população em situação de rua o grupo populacional heterogêneo que possui em comum pobreza extrema, os vínculos familiares interrompidos ou fragilizados e a inexistência de moradia convencional regular, e que utiliza os logradouros públicos e as áreas degradadas como espaço de moradia e de sustento, de forma temporária ou permanente, bem como as unidades de acolhimento para pernoite temporário ou como moradia provisória.', null, 'Disponível em: https://www.planalto.gov.br. Acesso em: 30 de maio 2023 (adaptado).'),
  ('fb0e3d63-e0d0-48df-9d23-c491c52a1096', 'e8107cbf-03ca-4d8c-af98-096ce82ebdd5', '2', null, 'enem-ppl-2023-motivador-2.jpg', 'Disponível em: https://archtrends.com/arquitetura-hostil/. Acesso em: 19 de jul. 2023.'),
  ('86b9d495-f4a9-4dca-8286-939f5e6da6cf', 'e8107cbf-03ca-4d8c-af98-096ce82ebdd5', '3', 'A palavra aporofobia, que significa aversão, medo e desprezo aos pobres e desfavorecidos financeiramente, tem ganhado holofotes com as denúncias feitas pelo padre Júlio Lancellotti, da Pastoral do Povo de Rua. Entre as fotos postadas em suas redes sociais, ele mostra elementos da chamada “arquitetura antipobres”, que impedem, nos espaços públicos, a estadia, o descanso ou a passagem de pessoas em situação de rua. “Grades, dutos de água, pedras pontiagudas. Há os que querem disfarçar com vasos e com paisagismo”, diz ele.', null, 'Disponível em: https://g1.globo.com. Acesso em: 23 jun. 2023 (adaptado).'),
  ('fc8b28af-9316-4dce-8122-3b3566c8553b', 'e8107cbf-03ca-4d8c-af98-096ce82ebdd5', '4', 'A perda de uma renda fixa fez Cris ir para a rua. Ela e o marido recebiam, até o início da pandemia de covid-19, pouco mais de um salário mínimo cada. Os dois perderam o emprego na mesma época e viram as economias derreterem. “A gente tinha economizado um dinheiro, mas zerou. A gente gostava de passear. Mas, com a pandemia, acabaram nossas economias. Aí ele me falou: ‘Vamos fazer o quê?’. Eu respondi: ‘Vamos pra rua’”, conta.

A falta de renda é a principal causa que leva uma pessoa a viver em situação de rua, afirma um pesquisador do Instituto de Pesquisa Aplicada (Ipea). “O fator econômico inclui falta de renda e de oportunidade de trabalho nos locais de moradia. Isso se manifesta também no caso de pessoas que até têm uma habitação longe dos grandes centros, mas passam a semana ou vários dias dormindo de forma improvisada nas ruas e trabalhando como lavador de carro, ambulante e outras coisas”, diz.', null, 'Disponível em: https://g1.globo.com. Acesso em: 23 jun. 2023 (adaptado).'),
  ('d78b0fa6-4031-4bed-b681-36aa1942fa59', 'e8107cbf-03ca-4d8c-af98-096ce82ebdd5', '5', null, 'enem-ppl-2023-motivador-5.jpg', 'Disponível em: https://g1.globo.com. Acesso em: 30 jun. 2023 (adaptado).'),
  ('1e7b5a0d-1fc5-4429-b9c0-43b54d7ba827', 'cc651d5e-6a89-45ab-ba7e-2317475adad8', '1', 'A expressão “cultura de periferia” passou a ser utilizada muito recentemente, seja nos movimentos sociais, seja nas pesquisas acadêmicas.

Ao ler o Manifesto da Antropofagia Periférica, texto inspirado no Manifesto Antropofágico do Modernismo brasileiro, e ao observar a forma como os diferentes coletivos utilizam a palavra “periferia”, é perceptível que ela assume um sentido para além daquele que a designa como uma relação de distância geográfica a partir de algum centro. “Periferia” assume um conjunto de representações simbólicas relacionadas à classe, etnia, lugar de moradia e condição do jovem na metrópole.', null, 'ALMEIDA, R. S. Cultura de periferia na periferia. Disponível em: https://diplomatique.org.br. Acesso em: 24 jun. 2024 (adaptado).'),
  ('fab45266-3b3a-4251-9fcf-92f16d0daf1f', 'cc651d5e-6a89-45ab-ba7e-2317475adad8', '2', 'A Periferia nos une pelo amor, pela dor e pela cor.
Dos becos e vielas há de vir a voz que grita contra o silêncio que nos pune. Eis que surge das ladeiras um povo lindo e inteligente galopando contra o passado. A favor de um futuro limpo, para todos os brasileiros.
A favor de um subúrbio que clama por arte e cultura, e universidade para a diversidade. Agogôs e tamborins acompanhados de violinos, só depois da aula.
Contra a arte patrocinada pelos que corrompem a liberdade de opção. Contra a arte fabricada para destruir o senso crítico, a emoção e a sensibilidade que nasce da múltipla escolha.
A Arte que liberta não pode vir da mão que escraviza.
A favor do batuque da cozinha que nasce na cozinha e sinhá não quer. Da poesia periférica que brota na porta do bar.
Do teatro que não vem do “ter ou não ter...”. Do cinema real que transmite ilusão.
Das Artes Plásticas, que, de concreto, quer substituir os barracos de madeiras.
Da Dança que desafoga no lago dos cisnes. Da Música que não embala os adormecidos.
Da Literatura das ruas despertando nas calçadas.
A Periferia unida, no centro de todas as coisas.', 'enem-ppl-2024-motivador-2.jpg', 'VAZ, S. Disponível em: www.novacultura.info. Acesso em: 24 maio 2024.'),
  ('a95ab3c4-bcc1-40dd-b528-14f09cf42e95', 'cc651d5e-6a89-45ab-ba7e-2317475adad8', '3', 'Galeria, lambe-lambe, favela grafitada, muro de casa, parede de escola. Eis alguns exemplos de obras visuais que se apropriam da arquitetura improvisada das cidades e interagem com a população. Essas intervenções artísticas são importantes porque transformam paisagens e passam mensagens de identidade, representatividade e justiça social.', 'enem-ppl-2024-motivador-3.jpg', 'Disponível em: https://expresso.estadao.com.br. Acesso em: 24 maio 2024 (adaptado).'),
  ('6d3d03cf-ca9d-4f07-bf88-b58292d3790c', 'cc651d5e-6a89-45ab-ba7e-2317475adad8', '4', 'Nascida na periferia da Grande Belo Horizonte (BH), produtora completa 15 anos de história:
“Não queremos ser uma exceção”

Fundada em Contagem, a empresa é uma verdadeira fábrica de filmes premiados. O catálogo foca em produções humanistas e com temas diversificados, e já soma mais de 50 prêmios desde sua criação.

A equipe é formada por diretores nascidos e criados na periferia de Contagem, onde não só encontraram boas histórias, mas também aprenderam na prática que a reprodução da realidade iria muito além de um set de gravação. Para os artistas, o diferencial da produtora é justamente o “olhar” para questões socialmente importantes que só as pessoas que cresceram em lugares esquecidos pelo poder público têm.', null, 'Disponível em: www.g1.globo.com.Acesso em: 25 jun. 2024 (adaptado).'),
  ('727284ac-ae47-4ef7-98fc-f61d0de16c63', '84de40f9-f257-421a-890b-384a79e38dfc', '1', 'Lei n. 8 069, de 13 de julho de 1990

Art. 3º A criança e o adolescente gozam de todos os direitos fundamentais inerentes à pessoa humana, sem prejuízo da proteção integral de que trata esta Lei, assegurando-se-lhes, porlei ou por outros meios, todas as oportunidades e facilidades, a fim de lhes facultar o desenvolvimento físico, mental, moral, espiritual e social, em condições de liberdade e de dignidade.', null, 'Disponível em: www.gov.br/planalto. Acesso em: 3 jul. 2025.'),
  ('c23af9aa-d3a3-4919-ba7b-565a9f25ae30', '84de40f9-f257-421a-890b-384a79e38dfc', '2', null, 'enem-ppl-2025-motivador-2.png', 'Disponível em: www.correiobraziliense.com.br. Acesso em: 4 jul. 2025 (adaptado).'),
  ('2c55b4db-6942-40e7-aa66-5eacfe8047bf', '84de40f9-f257-421a-890b-384a79e38dfc', '3', 'Sementes

Se tem muita pressão
Não desenvolve a semente
É a mesma coisa com a gente
Que é pra ser gentil
Como flor é pra florir
Mas sem água, Sol e tempo
Que botão vai se abrir?
É muito triste, muito cedo
É muito covarde
Cortar infâncias pela metade
Pra ser um adulto, sem tumulto, não existe atalho.', null, 'EMICIDA et al. Sementes. Rio de Janeiro: Sony Music; Warner, 2020 (fragmento).'),
  ('d24b0f10-8943-4436-bd34-e6a777c71746', '84de40f9-f257-421a-890b-384a79e38dfc', '4', null, 'enem-ppl-2025-motivador-4.png', 'Disponível em: www.trt24.jus.br. Acesso em: 11 jul. 2025.'),
  ('285ac32a-d248-4ee9-83b6-5467bf1cb573', '84de40f9-f257-421a-890b-384a79e38dfc', '5', null, 'enem-ppl-2025-motivador-5.png', 'Disponível em: www.gov.br/trabalho-e-emprego. Acesso em: 15 maio 2025 (adaptado). '),
  ('48338dd6-363a-42b3-b330-65ed300bf5a5', '84de40f9-f257-421a-890b-384a79e38dfc', '6', 'Nós, crianças, adolescentes e jovens, sujeitos sociais com prioridade absoluta prevista na Constituição Federal, vindos das mais diversas regiões, egressos e não egressos do trabalho infantil, escrevemos esta carta exigindo que os nossos direitos não sejam reduzidos. As propostas que visam reduzir a idade laboral de 16 para 14 anos são inconstitucionais. Consideramos a mudança prejudicial para o Estado Democrático de Direito
e para todo o povo brasileiro, em especial para a garantia dos direitos humanos de adolescentes e jovens de nosso país. Escrevemos não apenas por nós, mas por aproximadamente 30 mil crianças e adolescentes que sofreram acidentes graves enquanto trabalhavam e por todas as crianças e adolescentes que assumiram a responsabilidade de trabalhar.', null, 'Disponível em: https://fnpeti.org.br. Acesso em: 15 maio 2025 (adaptado).')
on conflict (id) do update set
  topic_id = excluded.topic_id,
  text_number = excluded.text_number,
  body_text = excluded.body_text,
  image_url = excluded.image_url,
  source_reference = excluded.source_reference;

insert into public.holidays (date, name, created_at)
values
  ('2026-01-01', 'Confraternização mundial', '2026-05-06 18:59:34.17557+00'),
  ('2026-02-17', 'Carnaval', '2026-05-06 18:59:34.17557+00'),
  ('2026-04-03', 'Sexta-feira Santa', '2026-05-06 18:59:34.17557+00'),
  ('2026-04-05', 'Páscoa', '2026-05-06 18:59:34.17557+00'),
  ('2026-04-21', 'Tiradentes', '2026-05-06 18:59:34.17557+00'),
  ('2026-05-01', 'Dia do trabalho', '2026-05-06 18:59:34.17557+00'),
  ('2026-06-04', 'Corpus Christi', '2026-05-06 18:59:34.17557+00'),
  ('2026-09-07', 'Independência do Brasil', '2026-05-06 18:59:34.17557+00'),
  ('2026-10-12', 'Nossa Senhora Aparecida', '2026-05-06 18:59:34.17557+00'),
  ('2026-11-02', 'Finados', '2026-05-06 18:59:34.17557+00'),
  ('2026-11-15', 'Proclamação da República', '2026-05-06 18:59:34.17557+00'),
  ('2026-11-20', 'Dia da consciência negra', '2026-05-06 18:59:34.17557+00'),
  ('2026-12-25', 'Natal', '2026-05-06 18:59:34.17557+00'),
  ('2027-01-01', 'Confraternização mundial', '2026-05-06 18:59:34.17557+00'),
  ('2027-02-09', 'Carnaval', '2026-05-06 18:59:34.17557+00'),
  ('2027-03-26', 'Sexta-feira Santa', '2026-05-06 18:59:34.17557+00'),
  ('2027-03-28', 'Páscoa', '2026-05-06 18:59:34.17557+00'),
  ('2027-04-21', 'Tiradentes', '2026-05-06 18:59:34.17557+00'),
  ('2027-05-01', 'Dia do trabalho', '2026-05-06 18:59:34.17557+00'),
  ('2027-05-27', 'Corpus Christi', '2026-05-06 18:59:34.17557+00'),
  ('2027-09-07', 'Independência do Brasil', '2026-05-06 18:59:34.17557+00'),
  ('2027-10-12', 'Nossa Senhora Aparecida', '2026-05-06 18:59:34.17557+00'),
  ('2027-11-02', 'Finados', '2026-05-06 18:59:34.17557+00'),
  ('2027-11-15', 'Proclamação da República', '2026-05-06 18:59:34.17557+00'),
  ('2027-11-20', 'Dia da consciência negra', '2026-05-06 18:59:34.17557+00'),
  ('2027-12-25', 'Natal', '2026-05-06 18:59:34.17557+00')
on conflict (date) do update set
  name = excluded.name,
  created_at = excluded.created_at;

commit;
