import { SubscriptionStatus } from '@repo/types';

export const USER_STATUS_MAP = {
  active: { label: "Ativo", colors: "bg-emerald-50 text-emerald-600" },
  inactive: { label: "Inativo", colors: "bg-slate-100 text-slate-500" },
  blocked: { label: "Bloqueado", colors: "bg-red-50 text-red-600" },
};

export const DELIVERY_STATUS_MAP = {
  corrected: { label: "Corrigida", colors: 'text-emerald-600 bg-emerald-50' },
  returned: { label: "Devolvida", colors: 'text-amber-600 bg-amber-50' },
  correcting: { label: "Em correção", colors: 'text-blue-600 bg-blue-50' },
}

 export const ESSAY_STATUS_MAP = {
    pending: { label: 'Pendente', textColor: 'text-primary' },
    draft: { label: 'Rascunho', textColor: 'text-slate-500' },
    corrected: { label: 'Corrigida', textColor: 'text-success' },
    correcting: { label: 'Em correção', textColor: 'text-secondary' },
    returned: { label: 'Devolvida', textColor: 'text-amber-700' },
  }

export const statusBadgeConfig: Record<SubscriptionStatus, { label: string; classes: string }> = {
  active: {
    label: "Ativo",
    classes: "bg-emerald-50! text-emerald-600!"
  },
  trial: {
    label: "Período de Teste",
    classes: "bg-blue-50 text-blue-600"
  },
  past_due: {
    label: "Atrasado",
    classes: "bg-amber-50 text-amber-600"
  },
  unpaid: {
    label: "Bloqueado",
    classes: "bg-red-50 text-red-600"
  },
  canceled: {
    label: "Cancelado",
    classes: "bg-slate-100 text-slate-500"
  },
};

export const AVAILABLE_COURSES = [
  "Administração",
  "Administração Hospitalar",
  "Administração Pública",
  "Agronegócio",
  "Agroindústria",
  "Agronomia",
  "Análise e Desenvolvimento de Sistemas",
  "Animação",
  "Antropologia",
  "Arquitetura e Urbanismo",
  "Artes",
  "Artes Gráficas",
  "Artes Plásticas",
  "Artes Visuais",
  "Automação Industrial",
  "Banco de Dados",
  "Biblioteconomia",
  "Biologia",
  "Biomedicina",
  "Ciência da Computação",
  "Ciência da Informação",
  "Ciências Contábeis",
  "Ciências Sociais",
  "Cinema",
  "Comunicação Institucional",
  "Comunicação Social",
  "Construção Civil",
  "Criação Gráfica",
  "Dança",
  "Desenho Industrial",
  "Desenho de Moda",
  "Desenvolvimento de Softwares",
  "Design",
  "Design de Interiores",
  "Design de Produto",
  "Direito",
  "Economia",
  "Economia Doméstica",
  "Educação Física",
  "Empreendedorismo",
  "Enfermagem",
  "Engenharia Aeronáutica",
  "Engenharia Ambiental",
  "Engenharia Biomédica",
  "Engenharia Bioquímica",
  "Engenharia Cartográfica",
  "Engenharia Civil",
  "Engenharia Elétrica",
  "Engenharia Eletrônica",
  "Engenharia Eletrotécnica",
  "Engenharia Florestal",
  "Engenharia Física",
  "Engenharia Geológica",
  "Engenharia Industrial",
  "Engenharia Mecatrônica",
  "Engenharia Mecânica",
  "Engenharia Metalúrgica",
  "Engenharia Naval",
  "Engenharia Nuclear",
  "Engenharia Química",
  "Engenharia Sanitária",
  "Engenharia Têxtil",
  "Engenharia de Alimentos",
  "Engenharia de Computação",
  "Engenharia de Controle e Automação",
  "Engenharia de Materiais",
  "Engenharia de Minas",
  "Engenharia de Petróleo",
  "Engenharia de Produção",
  "Engenharia de Produção de Materiais",
  "Engenharia de Recursos Hídricos",
  "Engenharia de Redes de Comunicação",
  "Engenharia de Telecomunicações",
  "Estatística",
  "Estudos Sociais",
  "Eventos",
  "Farmácia",
  "Filosofia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Fotografia",
  "Física",
  "Gastronomia",
  "Geofísica",
  "Geografia",
  "Geologia",
  "Geoprocessamento",
  "Gestão Comercial",
  "Gestão Financeira",
  "Gestão Logística",
  "Gestão da Informação",
  "Gestão da Produção Industrial",
  "Gestão da Segurança",
  "Gestão de Empresas",
  "Gestão de Negócios",
  "Gestão de Qualidade",
  "Gestão de Recursos Humanos",
  "Gestão de Serviços",
  "História",
  "Hotelaria",
  "Informática",
  "Jornalismo",
  "Letras",
  "Linguística",
  "Marketing",
  "Matemática",
  "Medicina",
  "Medicina Veterinária",
  "Meteorologia",
  "Microbiologia",
  "Música",
  "Negócios Imobiliários",
  "Negócios Internacionais",
  "Nutrição",
  "Oceanografia",
  "Odontologia",
  "Paisagismo",
  "Pedagogia",
  "Petróleo e Gás",
  "Produção Cultural",
  "Produção de Multimídia",
  "Psicologia",
  "Publicidade e Propaganda",
  "Química",
  "Radialismo",
  "Radiologia",
  "Relações Internacionais",
  "Relações Públicas",
  "Saúde Pública",
  "Segurança da Informação",
  "Seguros",
  "Serviço Social",
  "Sociologia",
  "Som e Imagem",
  "Tecnologia da Informação",
  "Tecnologia de Alimentos",
  "Teatro",
  "Teologia",
  "Terapia Ocupacional",
  "Turismo",
  "Zootecnia",
  "Outro"
];

export const transactionLabels: Record<string, string> = {
  new_subscription: 'Nova Assinatura',
  mentorship_bonus: 'Bônus de Mentoria',
  plan_renewal: 'Renovação de Assinatura',
  standalone_purchase: 'Compra de Crédito Avulso',
  essay_usage: 'Envio de Redação',
  plan_change: 'Mudança de Plano',
  administrative_adjustment: 'Ajuste Administrativo',
  essay_refund: 'Devolução de Redação',
  free_trial_grant: 'Crédito Gratuito', 
  subscription_reactivation: "Reativação da assinatura",
  mentorship_expiration: "Vencimento da mentoria",
  plan_expiration: "Expiração de créditos do plano",
};

export const COMPETENCIES = [
  { id: "C1", title: "Domínio da Norma Culta", description: "Demonstrar domínio da modalidade escrita formal da língua portuguesa." },
  { id: "C2", title: "Compreensão do Tema", description: "Compreender a proposta e aplicar conceitos dentro da estrutura dissertativo-argumentativa." },
  { id: "C3", title: "Organização de Ideias", description: "Selecionar e organizar informações em defesa de um ponto de vista." },
  { id: "C4", title: "Coesão Textual", description: "Demonstrar conhecimento dos mecanismos linguísticos necessários para a argumentação." },
  { id: "C5", title: "Proposta de Intervenção", description: "Elaborar proposta de intervenção detalhada respeitando os direitos humanos." },
];
