export const USER_STATUS_MAP = {
  active: { label: "Ativo", colors: "bg-emerald-50 text-emerald-600" },
  inactive: { label: "Inativo", colors: "bg-slate-100 text-slate-500" },
  blocked: { label: "Bloqueado", colors: "bg-red-50 text-red-600" },
};

export const DELIVERY_STATUS_MAP = {
  corrected: { label: "Corrigida", colors: 'text-emerald-600 bg-emerald-50' },
  returned: { label: "Devolvida", colors: 'text-amber-600 bg-amber-50' },
  correcting: { label: "Em correção", colors: 'text-blue-600 bg-blue-50' },
}

export const AVAILABLE_COURSES = [
  "Administração",
  "Administração Hospitalar",
  "Administração Pública",
  "Agronegócio",
  "Agroindústria",
  "Agronomia",
  "Análise e Desenvolvimento de Sistemas",
  "Animação",
  "Antropologia",
  "Arquitetura e Urbanismo",
  "Artes",
  "Artes Gráficas",
  "Artes Plásticas",
  "Artes Visuais",
  "Automação Industrial",
  "Banco de Dados",
  "Biblioteconomia",
  "Biologia",
  "Biomedicina",
  "Ciência da Computação",
  "Ciência da Informação",
  "Ciências Contábeis",
  "Ciências Sociais",
  "Cinema",
  "Comunicação Institucional",
  "Comunicação Social",
  "Construção Civil",
  "Criação Gráfica",
  "Dança",
  "Desenho Industrial",
  "Desenho de Moda",
  "Desenvolvimento de Softwares",
  "Design",
  "Design de Interiores",
  "Design de Produto",
  "Direito",
  "Economia",
  "Economia Doméstica",
  "Educação Física",
  "Empreendedorismo",
  "Enfermagem",
  "Engenharia Aeronáutica",
  "Engenharia Ambiental",
  "Engenharia Biomédica",
  "Engenharia Bioquímica",
  "Engenharia Cartográfica",
  "Engenharia Civil",
  "Engenharia Elétrica",
  "Engenharia Eletrônica",
  "Engenharia Eletrotécnica",
  "Engenharia Florestal",
  "Engenharia Física",
  "Engenharia Geológica",
  "Engenharia Industrial",
  "Engenharia Mecatrônica",
  "Engenharia Mecânica",
  "Engenharia Metalúrgica",
  "Engenharia Naval",
  "Engenharia Nuclear",
  "Engenharia Química",
  "Engenharia Sanitária",
  "Engenharia Têxtil",
  "Engenharia de Alimentos",
  "Engenharia de Computação",
  "Engenharia de Controle e Automação",
  "Engenharia de Materiais",
  "Engenharia de Minas",
  "Engenharia de Petróleo",
  "Engenharia de Produção",
  "Engenharia de Produção de Materiais",
  "Engenharia de Recursos Hídricos",
  "Engenharia de Redes de Comunicação",
  "Engenharia de Telecomunicações",
  "Estatística",
  "Estudos Sociais",
  "Eventos",
  "Farmácia",
  "Filosofia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Fotografia",
  "Física",
  "Gastronomia",
  "Geofísica",
  "Geografia",
  "Geologia",
  "Geoprocessamento",
  "Gestão Comercial",
  "Gestão Financeira",
  "Gestão Logística",
  "Gestão da Informação",
  "Gestão da Produção Industrial",
  "Gestão da Segurança",
  "Gestão de Empresas",
  "Gestão de Negócios",
  "Gestão de Qualidade",
  "Gestão de Recursos Humanos",
  "Gestão de Serviços",
  "História",
  "Hotelaria",
  "Informática",
  "Jornalismo",
  "Letras",
  "Linguística",
  "Marketing",
  "Matemática",
  "Medicina",
  "Medicina Veterinária",
  "Meteorologia",
  "Microbiologia",
  "Música",
  "Negócios Imobiliários",
  "Negócios Internacionais",
  "Nutrição",
  "Oceanografia",
  "Odontologia",
  "Paisagismo",
  "Pedagogia",
  "Petróleo e Gás",
  "Produção Cultural",
  "Produção de Multimídia",
  "Psicologia",
  "Publicidade e Propaganda",
  "Química",
  "Radialismo",
  "Radiologia",
  "Relações Internacionais",
  "Relações Públicas",
  "Saúde Pública",
  "Segurança da Informação",
  "Seguros",
  "Serviço Social",
  "Sociologia",
  "Som e Imagem",
  "Tecnologia da Informação",
  "Tecnologia de Alimentos",
  "Teatro",
  "Teologia",
  "Terapia Ocupacional",
  "Turismo",
  "Zootecnia",
  "Outro"
];